package com.gerenciadorrural.modules.platform.api;

import com.gerenciadorrural.infrastructure.database.PostgresTestEnvironment;
import com.nimbusds.jose.*; import com.nimbusds.jose.crypto.MACSigner; import com.nimbusds.jwt.*;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.*; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.*; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.web.servlet.MockMvc;
import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.sql.*; import java.time.*; import java.util.*; import java.util.concurrent.*;
import static org.assertj.core.api.Assertions.assertThat; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;

@ActiveProfiles("test") @SpringBootTest(properties={"app.security.supabase.mode=HMAC","app.security.supabase.algorithm=HS256","app.security.supabase.issuer=https://auth.example.test/auth/v1","app.security.supabase.hmac-secret=test-only-hmac-key-with-at-least-32-bytes","app.security.supabase.audiences=authenticated","app.security.supabase.accepted-token-roles=authenticated"}) @AutoConfigureMockMvc
class InvitationConcurrencyIntegrationTest extends com.gerenciadorrural.infrastructure.database.SpringPostgresTestSupport {
 private static final String SECRET="test-only-hmac-key-with-at-least-32-bytes",ISSUER="https://auth.example.test/auth/v1"; @Autowired MockMvc mvc;
 @BeforeEach void clean()throws Exception{PostgresTestEnvironment.clearUsers();}
 @Test void sameTokenAcceptanceHasOneEffectAcrossFiveRealHttpRaces()throws Exception{for(int i=0;i<5;i++){UUID org=UUID.randomUUID(),user=UUID.randomUUID(),inv=UUID.randomUUID();String raw="token-"+UUID.randomUUID();seed(org,user,inv,hash(raw));List<Integer> status=race(raw,token(user,"invitee@example.test"));assertThat(status).contains(204);assertThat(count("organization_memberships","tenant_id",org)).isEqualTo(1);assertThat(count("platform_admin_events","organization_id",org)).isEqualTo(1);assertThat(text(inv,"organization_invitations","status")).isEqualTo("ACCEPTED");}}
 private void seed(UUID o,UUID u,UUID i,String h)throws Exception{try(Connection c=PostgresTestEnvironment.adminConnection();Statement s=c.createStatement()){s.execute("insert into app.users(id,email,status) values('"+u+"','invitee@example.test','ACTIVE')");s.execute("insert into app.organizations(id,name,status) values('"+o+"','O','ACTIVE')");s.execute("insert into app.organization_invitations(id,organization_id,invited_email,normalized_email,role_key,farm_scope_mode,status,token_hash,invited_by_user_id,expires_at) values('"+i+"','"+o+"','invitee@example.test','invitee@example.test','VIEWER','ALL_FARMS','PENDING','"+h+"','"+u+"',current_timestamp+interval '1 day')");}}
 private List<Integer> race(String raw,String jwt)throws Exception{ExecutorService e=Executors.newFixedThreadPool(2);CyclicBarrier b=new CyclicBarrier(2);try{Future<Integer>a=e.submit(()->call(b,raw,jwt)),d=e.submit(()->call(b,raw,jwt));return List.of(a.get(20,TimeUnit.SECONDS),d.get(20,TimeUnit.SECONDS));}finally{e.shutdownNow();assertThat(e.awaitTermination(10,TimeUnit.SECONDS)).isTrue();}}
 private int call(CyclicBarrier b,String raw,String jwt)throws Exception{b.await(10,TimeUnit.SECONDS);return mvc.perform(post("/api/v1/invitations/"+raw+"/accept").header(HttpHeaders.AUTHORIZATION,"Bearer "+jwt)).andReturn().getResponse().getStatus();}
 private static String hash(String s)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));} private int count(String table,String col,Object value)throws Exception{try(Connection c=PostgresTestEnvironment.adminConnection();PreparedStatement p=c.prepareStatement("select count(*) from app."+table+" where "+col+"=?")){p.setObject(1,value);try(ResultSet r=p.executeQuery()){r.next();return r.getInt(1);}}} private String text(UUID id,String table,String col)throws Exception{try(Connection c=PostgresTestEnvironment.adminConnection();Statement s=c.createStatement();ResultSet r=s.executeQuery("select "+col+" from app."+table+" where id='"+id+"'")){r.next();return r.getString(1);}}
 private static String token(UUID user,String email)throws Exception{JWTClaimsSet c=new JWTClaimsSet.Builder().issuer(ISSUER).audience("authenticated").subject(user.toString()).claim("role","authenticated").claim("email",email).issueTime(new java.util.Date()).expirationTime(java.util.Date.from(Instant.now().plusSeconds(300))).build();SignedJWT j=new SignedJWT(new JWSHeader(JWSAlgorithm.HS256),c);j.sign(new MACSigner(SECRET.getBytes()));return j.serialize();}
}
