package com.gerenciadorrural.modules.herd.infrastructure;
import com.gerenciadorrural.modules.herd.domain.*; import com.gerenciadorrural.shared.tenancy.TenantId; import org.springframework.jdbc.core.namedparam.*; import org.springframework.stereotype.Repository; import java.time.*; import java.util.*;
@Repository public class JdbcHerdReproductionRepository implements HerdReproductionRepository {private final NamedParameterJdbcTemplate j;public JdbcHerdReproductionRepository(NamedParameterJdbcTemplate j){this.j=j;}private MapSqlParameterSource p(TenantId t,UUID f){return new MapSqlParameterSource("tenant",t.value()).addValue("farm",f);}
 private static final String CURRENT_MOTHER=" from app.animal_pregnancies p join app.animals mother on mother.tenant_id=p.tenant_id and mother.id=p.mother_animal_id where p.tenant_id=:tenant and mother.farm_id=:farm ";
 public Optional<Pregnancy> find(TenantId t,UUID f,UUID id,boolean lock){return j.query("select p.*"+CURRENT_MOTHER+"and p.id=:id"+(lock?" for update of p":""),p(t,f).addValue("id",id),this::map).stream().findFirst();}
 public Optional<Pregnancy> findByOperation(TenantId t,UUID f,UUID op){return j.query("select p.*"+CURRENT_MOTHER+"and p.operation_id=:op",p(t,f).addValue("op",op),this::map).stream().findFirst();}
 public Pregnancy insert(Pregnancy x){return j.query("insert into app.animal_pregnancies(id,tenant_id,farm_id,mother_animal_id,service_type,service_on,sire_reference,expected_calving_on,operation_id,command_payload,created_by) values(:id,:tenant,:farm,:mother,:type,:service,:sire,:due,:op,:payload,:actor) returning *",new MapSqlParameterSource().addValue("id",x.id()).addValue("tenant",x.tenantId().value()).addValue("farm",x.farmId()).addValue("mother",x.motherAnimalId()).addValue("type",x.serviceType().name()).addValue("service",x.serviceOn()).addValue("sire",x.sireReference()).addValue("due",x.expectedCalvingOn()).addValue("op",x.operationId()).addValue("payload",x.commandPayload()).addValue("actor",null),this::map).getFirst();}
 public Optional<Pregnancy> transition(TenantId t,UUID f,UUID id,long v,PregnancyStatus s,LocalDate d,PregnancyTerminationReason r,UUID calf){return j.query("update app.animal_pregnancies p set status=:status,confirmed_on=case when :status='CONFIRMED' then :date else p.confirmed_on end,ended_on=case when :status in ('TERMINATED','CALVED') then :date else p.ended_on end,termination_reason=:reason,calf_animal_id=:calf,version=p.version+1,updated_at=current_timestamp from app.animals mother where mother.tenant_id=p.tenant_id and mother.id=p.mother_animal_id and p.tenant_id=:tenant and mother.farm_id=:farm and p.id=:id and p.version=:version returning p.*",p(t,f).addValue("id",id).addValue("version",v).addValue("status",s.name()).addValue("date",d).addValue("reason",r==null?null:r.name()).addValue("calf",calf),this::map).stream().findFirst();}
 public List<Pregnancy> list(TenantId t,UUID f,UUID mother,int size,long offset){return j.query("select p.*"+CURRENT_MOTHER+"and p.mother_animal_id=:mother order by p.service_on desc,p.id desc limit :size offset :offset",p(t,f).addValue("mother",mother).addValue("size",size).addValue("offset",offset),this::map);}
 public long count(TenantId t,UUID f,UUID mother){Long n=j.queryForObject("select count(*)"+CURRENT_MOTHER+"and p.mother_animal_id=:mother",p(t,f).addValue("mother",mother),Long.class);return n==null?0:n;}
 private Pregnancy map(java.sql.ResultSet r,int n)throws java.sql.SQLException{return new Pregnancy(r.getObject("id",UUID.class),new TenantId(r.getObject("tenant_id",UUID.class)),r.getObject("farm_id",UUID.class),r.getObject("mother_animal_id",UUID.class),ReproductionServiceType.valueOf(r.getString("service_type")),r.getObject("service_on",LocalDate.class),r.getString("sire_reference"),r.getObject("expected_calving_on",LocalDate.class),PregnancyStatus.valueOf(r.getString("status")),r.getObject("confirmed_on",LocalDate.class),r.getObject("ended_on",LocalDate.class),r.getString("termination_reason")==null?null:PregnancyTerminationReason.valueOf(r.getString("termination_reason")),r.getObject("calf_animal_id",UUID.class),r.getObject("operation_id",UUID.class),r.getString("command_payload"),r.getLong("version"));}}
