package com.gerenciadorrural.modules.herd.infrastructure;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.gerenciadorrural.modules.herd.domain.*;
import com.gerenciadorrural.shared.tenancy.TenantId;
import org.springframework.jdbc.core.namedparam.*;
import org.springframework.stereotype.Repository;
import java.time.*;
import java.util.*;

@Repository public class JdbcAnimalEventRepository implements AnimalEventRepository {
 private final NamedParameterJdbcTemplate jdbc; private final ObjectMapper mapper;
 public JdbcAnimalEventRepository(NamedParameterJdbcTemplate jdbc,ObjectMapper mapper){this.jdbc=jdbc;this.mapper=mapper;}
 public void lockOperation(TenantId t,UUID f,UUID o){jdbc.query("select pg_advisory_xact_lock(hashtextextended(:key,0))",new MapSqlParameterSource("key",t.value()+":"+f+":"+o),r->{});}
 public void record(TenantId t,UUID f,UUID a,AnimalEventType type,UUID op,UUID actor,LocalDate occurred,long version,AnimalEventDetails details){jdbc.update("insert into app.animal_events (id,tenant_id,farm_id,animal_id,event_type,operation_id,actor_user_id,occurred_on,resulting_version,payload) values (:id,:tenantId,:farmId,:animalId,:type,:operationId,:actor,:occurred,:version,cast(:details as jsonb))",p(t,f,a).addValue("id",UUID.randomUUID()).addValue("type",type.name()).addValue("operationId",op).addValue("actor",actor).addValue("occurred",occurred).addValue("version",version).addValue("details",json(details)));}
 public void recordMovement(TenantId t,UUID f,UUID a,UUID op,UUID actor,LocalDate occurred,long version,MovedEventDetails details){UUID event=UUID.randomUUID();jdbc.update("insert into app.animal_events (id,tenant_id,farm_id,animal_id,event_type,operation_id,actor_user_id,occurred_on,resulting_version,payload) values (:id,:tenantId,:farmId,:animalId,'MOVED',:operationId,:actor,:occurred,:version,cast(:details as jsonb))",p(t,f,a).addValue("id",event).addValue("operationId",op).addValue("actor",actor).addValue("occurred",occurred).addValue("version",version).addValue("details",json(details)));jdbc.update("insert into app.herd_movements(event_id,tenant_id,farm_id,animal_id,operation_id,source_paddock_id,destination_paddock_id) values(:eventId,:tenantId,:farmId,:animalId,:operationId,:source,:destination)",p(t,f,a).addValue("eventId",event).addValue("operationId",op).addValue("source",details.sourcePaddockId()).addValue("destination",details.destinationPaddockId()));}
 public Optional<AnimalEvent> findByOperation(TenantId t,UUID f,UUID o){return jdbc.query(select()+" where tenant_id=:tenantId and farm_id=:farmId and operation_id=:operationId",new MapSqlParameterSource().addValue("tenantId",t.value()).addValue("farmId",f).addValue("operationId",o),this::map).stream().findFirst();}
 public List<AnimalEvent> history(TenantId t,UUID f,UUID a,AnimalEventType type,int size,long offset){MapSqlParameterSource parameters=p(t,f,a).addValue("size",size).addValue("offset",offset);String filter="";if(type!=null){filter=" and event_type=:type";parameters.addValue("type",type.name());}return jdbc.query(select()+" where tenant_id=:tenantId and farm_id=:farmId and animal_id=:animalId"+filter+" order by recorded_at desc,id desc limit :size offset :offset",parameters,this::map);}
 public long count(TenantId t,UUID f,UUID a,AnimalEventType type){MapSqlParameterSource parameters=p(t,f,a);String filter="";if(type!=null){filter=" and event_type=:type";parameters.addValue("type",type.name());}Long n=jdbc.queryForObject("select count(*) from app.animal_events where tenant_id=:tenantId and farm_id=:farmId and animal_id=:animalId"+filter,parameters,Long.class);return n==null?0:n;}
 private static String select(){return "select id,animal_id,event_type,operation_id,actor_user_id,occurred_on,recorded_at,resulting_version,payload from app.animal_events";} private static MapSqlParameterSource p(TenantId t,UUID f,UUID a){return new MapSqlParameterSource().addValue("tenantId",t.value()).addValue("farmId",f).addValue("animalId",a);}
 private String json(AnimalEventDetails d){try{return mapper.writeValueAsString(d);}catch(JsonProcessingException e){throw new IllegalStateException("Não foi possível serializar detalhes do evento",e);}}
 private AnimalEvent map(java.sql.ResultSet r,int n)throws java.sql.SQLException{AnimalEventType type=AnimalEventType.valueOf(r.getString("event_type"));try{JsonNode details=mapper.readTree(r.getString("payload"));return new AnimalEvent(r.getObject("id",UUID.class),r.getObject("animal_id",UUID.class),type,r.getObject("operation_id",UUID.class),r.getObject("actor_user_id",UUID.class),r.getObject("occurred_on",LocalDate.class),r.getObject("recorded_at",OffsetDateTime.class).toInstant(),r.getLong("resulting_version"),typed(type,details));}catch(JsonProcessingException e){throw new java.sql.SQLException("Detalhes de evento inválidos",e);}}
 private AnimalEventDetails typed(AnimalEventType type,JsonNode details)throws JsonProcessingException{return switch(type){case CREATED->mapper.treeToValue(details,CreatedEventDetails.class);case CORRECTED->mapper.treeToValue(details,CorrectedEventDetails.class);case SOLD,DECEASED->mapper.treeToValue(details,LifecycleEventDetails.class);case MOVED->mapper.treeToValue(details,MovedEventDetails.class);};}
}
