package com.gerenciadorrural.modules.herd.infrastructure;
import com.gerenciadorrural.modules.herd.domain.HerdTransferRepository; import com.gerenciadorrural.shared.tenancy.TenantId; import org.springframework.jdbc.core.namedparam.*; import org.springframework.stereotype.Repository; import java.time.*; import java.util.*;
@Repository public class JdbcHerdTransferRepository implements HerdTransferRepository {
 private final NamedParameterJdbcTemplate jdbc; public JdbcHerdTransferRepository(NamedParameterJdbcTemplate jdbc){this.jdbc=jdbc;}
 public void lockOperation(TenantId t,UUID o){jdbc.query("select pg_advisory_xact_lock(hashtextextended(:key,0))",new MapSqlParameterSource("key",t.value()+":transfer:"+o),r->{});} public Optional<String> payload(TenantId t,UUID o){return jdbc.query("select command_payload from app.herd_transfer_operations where tenant_id=:t and operation_id=:o",p(t).addValue("o",o),(r,n)->r.getString(1)).stream().findFirst();} public void saveOperation(TenantId t,UUID o,String v){jdbc.update("insert into app.herd_transfer_operations(tenant_id,operation_id,command_payload) values(:t,:o,:v)",p(t).addValue("o",o).addValue("v",v));}
 public Optional<Farm> lockFarm(TenantId t,UUID id){return jdbc.query("select id,name from app.farms where tenant_id=:t and id=:id for update",p(t).addValue("id",id),(r,n)->new Farm(r.getObject(1,UUID.class),r.getString(2))).stream().findFirst();} public boolean canAccessFarm(TenantId t,UUID membership,String scope,UUID farm){Long n;if("ALL_FARMS".equals(scope))n=jdbc.queryForObject("select count(*) from app.farms where tenant_id=:t and id=:f",p(t).addValue("f",farm),Long.class);else n=jdbc.queryForObject("select count(*) from app.membership_farm_scopes where tenant_id=:t and membership_id=:m and farm_id=:f",p(t).addValue("m",membership).addValue("f",farm),Long.class);return n!=null&&n>0;}
 public boolean identificationExists(TenantId t,UUID farm,String identification,UUID excluded){Long n=jdbc.queryForObject("select count(*) from app.animals where tenant_id=:t and farm_id=:f and id<>:id and lower(regexp_replace(identification,'(^[[:space:]]+|[[:space:]]+$)','g'))=lower(regexp_replace(:x,'(^[[:space:]]+|[[:space:]]+$)','g'))",p(t).addValue("f",farm).addValue("id",excluded).addValue("x",identification),Long.class);return n!=null&&n>0;}
 public void insert(Row r,TenantId t){jdbc.update("insert into app.animal_transfers(id,tenant_id,animal_id,operation_id,source_farm_id,destination_farm_id,source_farm_name,destination_farm_name,destination_paddock_id,destination_paddock_name,occurred_on,actor_user_id,original_expected_version,resulting_version,notes) values(:id,:t,:a,:o,:s,:d,:sn,:dn,:p,:pn,:on,:actor,:ev,:rv,:notes)",p(t).addValue("id",r.id()).addValue("a",r.animalId()).addValue("o",r.operationId()).addValue("s",r.sourceFarmId()).addValue("d",r.destinationFarmId()).addValue("sn",r.sourceFarmName()).addValue("dn",r.destinationFarmName()).addValue("p",r.destinationPaddockId()).addValue("pn",r.destinationPaddockName()).addValue("on",r.occurredOn()).addValue("actor",r.actorUserId()).addValue("ev",r.originalExpectedVersion()).addValue("rv",r.resultingVersion()).addValue("notes",r.notes()));}
 public List<Row> byOperation(TenantId t,UUID o){return jdbc.query(select()+" where tenant_id=:t and operation_id=:o order by animal_id",p(t).addValue("o",o),JdbcHerdTransferRepository::row);} public Optional<Row> detail(TenantId t,UUID farm,UUID id){return jdbc.query(select()+" where tenant_id=:t and id=:id and (source_farm_id=:f or destination_farm_id=:f)",p(t).addValue("f",farm).addValue("id",id),JdbcHerdTransferRepository::row).stream().findFirst();}
 public Page page(TenantId t,UUID farm,String direction,UUID animal,int size,long offset){String w=switch(direction){case "IN"->"destination_farm_id=:f";case "OUT"->"source_farm_id=:f";default->"(source_farm_id=:f or destination_farm_id=:f)";};var q=p(t).addValue("f",farm);if(animal!=null){w+=" and animal_id=:a";q.addValue("a",animal);}List<Row> items=jdbc.query(select()+" where tenant_id=:t and "+w+" order by recorded_at desc,id desc limit "+size+" offset "+offset,q,JdbcHerdTransferRepository::row);Long total=jdbc.queryForObject("select count(*) from app.animal_transfers where tenant_id=:t and "+w,q,Long.class);return new Page(items,total==null?0:total);}
 private static String select(){return "select id,animal_id,operation_id,source_farm_id,destination_farm_id,source_farm_name,destination_farm_name,destination_paddock_id,destination_paddock_name,occurred_on,recorded_at,actor_user_id,original_expected_version,resulting_version,notes from app.animal_transfers";} private static Row row(java.sql.ResultSet r,int n)throws java.sql.SQLException{return new Row(r.getObject(1,UUID.class),r.getObject(2,UUID.class),r.getObject(3,UUID.class),r.getObject(4,UUID.class),r.getObject(5,UUID.class),r.getString(6),r.getString(7),r.getObject(8,UUID.class),r.getString(9),r.getObject(10,LocalDate.class),r.getObject(11,OffsetDateTime.class).toInstant(),r.getObject(12,UUID.class),r.getLong(13),r.getLong(14),r.getString(15));} private static MapSqlParameterSource p(TenantId t){return new MapSqlParameterSource("t",t.value());}
}
