package com.gerenciadorrural.modules.herd.infrastructure;
import com.gerenciadorrural.modules.herd.domain.*; import com.gerenciadorrural.shared.tenancy.TenantId; import org.springframework.jdbc.core.namedparam.*; import org.springframework.stereotype.Repository; import java.math.*; import java.time.*; import java.util.*;
@Repository public class JdbcHerdManagementRepository implements HerdManagementRepository {private final NamedParameterJdbcTemplate j; public JdbcHerdManagementRepository(NamedParameterJdbcTemplate j){this.j=j;} private MapSqlParameterSource p(TenantId t,UUID f,UUID a){return new MapSqlParameterSource().addValue("tenant",t.value()).addValue("farm",f).addValue("animal",a);}
 public Optional<String> operation(TenantId t,UUID f,UUID o){return j.query("select command_payload from app.herd_management_operations where tenant_id=:tenant and farm_id=:farm and operation_id=:op",p(t,f,o).addValue("op",o),(r,n)->r.getString(1)).stream().findFirst();} public void saveOperation(TenantId t,UUID f,UUID o,String type,String x){j.update("insert into app.herd_management_operations(tenant_id,farm_id,operation_id,command_type,command_payload) values(:tenant,:farm,:op,:type,:x)",p(t,f,o).addValue("op",o).addValue("type",type).addValue("x",x));}
 public void weight(TenantId t,UUID f,UUID a,UUID o,LocalDate d,BigDecimal k,String n,UUID actor){j.update("insert into app.animal_weight_measurements(id,tenant_id,farm_id,animal_id,operation_id,measured_on,weight_kg,notes,actor_user_id) values(:id,:tenant,:farm,:animal,:op,:d,:k,:n,:actor)",p(t,f,a).addValue("id",UUID.randomUUID()).addValue("op",o).addValue("d",d).addValue("k",k).addValue("n",n).addValue("actor",actor));}
 public void treatment(TenantId t,UUID f,UUID a,UUID o,HealthTreatmentType type,LocalDate d,String product,String protocol,LocalDate due,String n,UUID actor){j.update("insert into app.animal_health_treatments(id,tenant_id,farm_id,animal_id,operation_id,treatment_type,occurred_on,product,protocol,next_due_on,notes,actor_user_id) values(:id,:tenant,:farm,:animal,:op,:type,:d,:product,:protocol,:due,:n,:actor)",p(t,f,a).addValue("id",UUID.randomUUID()).addValue("op",o).addValue("type",type.name()).addValue("d",d).addValue("product",product).addValue("protocol",protocol).addValue("due",due).addValue("n",n).addValue("actor",actor));}
 public List<Weight> weights(TenantId t,UUID f,UUID a,int s,long o){return j.query("select id,operation_id,measured_on,weight_kg,notes,actor_user_id,recorded_at from app.animal_weight_measurements where tenant_id=:tenant and farm_id=:farm and animal_id=:animal order by measured_on desc,recorded_at desc,id desc limit :s offset :o",p(t,f,a).addValue("s",s).addValue("o",o),(r,n)->new Weight(r.getObject(1,UUID.class),r.getObject(2,UUID.class),r.getObject(3,LocalDate.class),r.getBigDecimal(4),r.getString(5),r.getObject(6,UUID.class),r.getObject(7,OffsetDateTime.class).toInstant()));} public long weightCount(TenantId t,UUID f,UUID a){return j.queryForObject("select count(*) from app.animal_weight_measurements where tenant_id=:tenant and farm_id=:farm and animal_id=:animal",p(t,f,a),Long.class);}
 public List<Treatment> treatments(TenantId t,UUID f,UUID a,int s,long o){return j.query("select id,operation_id,treatment_type,occurred_on,product,protocol,next_due_on,notes,actor_user_id,recorded_at from app.animal_health_treatments where tenant_id=:tenant and farm_id=:farm and animal_id=:animal order by occurred_on desc,recorded_at desc,id desc limit :s offset :o",p(t,f,a).addValue("s",s).addValue("o",o),(r,n)->new Treatment(r.getObject(1,UUID.class),r.getObject(2,UUID.class),HealthTreatmentType.valueOf(r.getString(3)),r.getObject(4,LocalDate.class),r.getString(5),r.getString(6),r.getObject(7,LocalDate.class),r.getString(8),r.getObject(9,UUID.class),r.getObject(10,OffsetDateTime.class).toInstant()));} public long treatmentCount(TenantId t,UUID f,UUID a){return j.queryForObject("select count(*) from app.animal_health_treatments where tenant_id=:tenant and farm_id=:farm and animal_id=:animal",p(t,f,a),Long.class);}
 public static final String PENDING_SQL="""
  with active as (select id,identification,name,farm_id from app.animals where tenant_id=:tenant and farm_id=:farm and status='ACTIVE'),
  lw as (select distinct on (w.animal_id) w.animal_id,w.measured_on from app.animal_weight_measurements w join active a on a.id=w.animal_id where w.tenant_id=:tenant order by w.animal_id,w.measured_on desc,w.recorded_at desc,w.id desc),
  lh as (select distinct on (h.animal_id,h.treatment_type) h.animal_id,h.treatment_type,h.occurred_on,h.next_due_on from app.animal_health_treatments h join active a on a.id=h.animal_id where h.tenant_id=:tenant and h.treatment_type in ('VACCINATION','DEWORMING') order by h.animal_id,h.treatment_type,h.occurred_on desc,h.recorded_at desc,h.id desc),
  items as (
   select case treatment_type when 'VACCINATION' then 'VACCINATION_DUE' else 'DEWORMING_DUE' end type,a.id animal_id,a.identification,a.name,a.farm_id,lh.next_due_on due_on,null::uuid pregnancy_id,lh.treatment_type,lh.occurred_on last_performed_on,null::date last_weight_on from lh join active a on a.id=lh.animal_id where lh.next_due_on<=:reference
   union all select 'WEIGHING_DUE',a.id,a.identification,a.name,a.farm_id,coalesce(lw.measured_on,:cutoff),null,null,null,lw.measured_on from active a left join lw on lw.animal_id=a.id where lw.measured_on is null or lw.measured_on<=:cutoff
   union all select case when p.expected_calving_on<:reference then 'CALVING_OVERDUE' else 'CALVING_UPCOMING' end,a.id,a.identification,a.name,a.farm_id,p.expected_calving_on,p.id,null,null,null from app.animal_pregnancies p join active a on a.id=p.mother_animal_id where p.tenant_id=:tenant and p.status in ('POSSIBLE','CONFIRMED') and p.expected_calving_on<=( :reference + :upcoming) )
  """;
 private MapSqlParameterSource pendingParams(TenantId t,UUID f,LocalDate reference,int weighingDays,int upcomingDays,PendingWorkType type,UUID animal){return new MapSqlParameterSource().addValue("tenant",t.value()).addValue("farm",f).addValue("reference",reference).addValue("cutoff",reference.minusDays(weighingDays)).addValue("upcoming",upcomingDays).addValue("type",type==null?null:type.name()).addValue("animal",animal);}
 public List<Pending> pending(TenantId t,UUID f,LocalDate reference,int weighingDays,int upcomingDays,PendingWorkType type,UUID animal,int size,long offset){String sql=PENDING_SQL+" select * from items where (cast(:type as text) is null or type=:type) and (cast(:animal as uuid) is null or animal_id=:animal) order by due_on asc,type asc,animal_id asc,pregnancy_id asc nulls first limit :size offset :offset";return j.query(sql,pendingParams(t,f,reference,weighingDays,upcomingDays,type,animal).addValue("size",size).addValue("offset",offset),(r,n)->new Pending(PendingWorkType.valueOf(r.getString("type")),r.getObject("animal_id",UUID.class),r.getString("identification"),r.getString("name"),r.getObject("farm_id",UUID.class),r.getObject("due_on",LocalDate.class),r.getObject("pregnancy_id",UUID.class),r.getString("treatment_type")==null?null:HealthTreatmentType.valueOf(r.getString("treatment_type")),r.getObject("last_performed_on",LocalDate.class),r.getObject("last_weight_on",LocalDate.class)));}
 public long pendingCount(TenantId t,UUID f,LocalDate reference,int weighingDays,int upcomingDays,PendingWorkType type,UUID animal){Long count=j.queryForObject(PENDING_SQL+" select count(*) from items where (cast(:type as text) is null or type=:type) and (cast(:animal as uuid) is null or animal_id=:animal)",pendingParams(t,f,reference,weighingDays,upcomingDays,type,animal),Long.class);return count==null?0:count;}
}
