package com.gerenciadorrural.modules.herd.infrastructure;

import com.gerenciadorrural.modules.herd.domain.*;
import com.gerenciadorrural.shared.tenancy.TenantId;
import org.springframework.jdbc.core.namedparam.*;
import org.springframework.stereotype.Repository;
import java.time.LocalDate;
import java.util.*;

@Repository public class JdbcPaddockRepository implements PaddockRepository {
 private final NamedParameterJdbcTemplate jdbc; public JdbcPaddockRepository(NamedParameterJdbcTemplate jdbc){this.jdbc=jdbc;}
 public Optional<PaddockSummary> find(TenantId t,UUID f,UUID id){return jdbc.query(select()+" where p.tenant_id=:tenantId and p.farm_id=:farmId and p.id=:id",p(t,f,id),JdbcPaddockRepository::map).stream().findFirst();}
 public Optional<PaddockSummary> lock(TenantId t,UUID f,UUID id){return jdbc.query(select()+" where p.tenant_id=:tenantId and p.farm_id=:farmId and p.id=:id for update",p(t,f,id),JdbcPaddockRepository::map).stream().findFirst();}
 public Optional<PaddockSummary> create(TenantId t,UUID f,PaddockSummary x){return jdbc.query("insert into app.paddocks(id,tenant_id,farm_id,name,code,status,version) values(:id,:tenantId,:farmId,:name,:code,:status,0) returning id,name,code,status,version",p(t,f,x.id()).addValue("name",x.name()).addValue("code",x.code()).addValue("status",x.status().name()),(r,n)->new PaddockSummary(r.getObject("id",UUID.class),r.getString("name"),r.getString("code"),PaddockStatus.valueOf(r.getString("status")),r.getLong("version"))).stream().findFirst();}
 public Optional<PaddockSummary> update(TenantId t,UUID f,PaddockSummary x,long expected){return jdbc.query("update app.paddocks set name=:name,code=:code,status=:status,version=version+1,updated_at=current_timestamp where tenant_id=:tenantId and farm_id=:farmId and id=:id and version=:expected returning id,name,code,status,version",p(t,f,x.id()).addValue("name",x.name()).addValue("code",x.code()).addValue("status",x.status().name()).addValue("expected",expected),(r,n)->new PaddockSummary(r.getObject("id",UUID.class),r.getString("name"),r.getString("code"),PaddockStatus.valueOf(r.getString("status")),r.getLong("version"))).stream().findFirst();}
 public PaddockPage list(TenantId t,UUID f,PaddockStatus status,String search,int page,int size){var q=p(t,f,null).addValue("limit",size).addValue("offset",(long)page*size);StringBuilder w=new StringBuilder(" where p.tenant_id=:tenantId and p.farm_id=:farmId");if(status!=null){w.append(" and p.status=:status");q.addValue("status",status.name());}if(search!=null){w.append(" and (lower(p.name) like :search escape '\\' or lower(coalesce(p.code,'')) like :search escape '\\')");q.addValue("search","%"+escape(search.toLowerCase(Locale.ROOT))+"%");}String from=" from app.paddocks p left join app.animals a on a.tenant_id=p.tenant_id and a.farm_id=p.farm_id and a.paddock_id=p.id ";var items=jdbc.query("select p.id,p.name,p.code,p.status,p.version,count(a.id) occupancy"+from+w+" group by p.id,p.name,p.code,p.status,p.version order by lower(p.name),p.id limit :limit offset :offset",q,JdbcPaddockRepository::map);Long total=jdbc.queryForObject("select count(*) from app.paddocks p"+w,q,Long.class);return new PaddockPage(items,page,size,total==null?0:total);}
 public long occupancy(TenantId t,UUID f,UUID id){Long n=jdbc.queryForObject("select count(*) from app.animals where tenant_id=:tenantId and farm_id=:farmId and paddock_id=:id",p(t,f,id),Long.class);return n==null?0:n;}
 public Map<HerdAnimalStatus,Long> occupancyByStatus(TenantId t,UUID f,UUID id){Map<HerdAnimalStatus,Long> r=new EnumMap<>(HerdAnimalStatus.class);jdbc.query("select status,count(*) n from app.animals where tenant_id=:tenantId and farm_id=:farmId and paddock_id=:id group by status",p(t,f,id),(rs,n)->{r.put(HerdAnimalStatus.valueOf(rs.getString("status")),rs.getLong("n"));return 0;});return r;}
 public HerdAnimalPage animals(TenantId t,UUID f,UUID id,int page,int size){var q=p(t,f,id).addValue("limit",size).addValue("offset",(long)page*size);var rows=jdbc.query(animalSelect()+" where a.tenant_id=:tenantId and a.farm_id=:farmId and a.paddock_id=:id order by lower(a.identification),a.id limit :limit offset :offset",q,JdbcPaddockRepository::animal);Long total=jdbc.queryForObject("select count(*) from app.animals a where a.tenant_id=:tenantId and a.farm_id=:farmId and a.paddock_id=:id",q,Long.class);return new HerdAnimalPage(rows,page,size,total==null?0:total);}
 private static String select(){return "select p.id,p.name,p.code,p.status,p.version,0::bigint occupancy from app.paddocks p";} private static String animalSelect(){return "select a.id,a.identification,a.name,a.sex,a.birth_date,a.status,a.version,p.id paddock_id,p.name paddock_name,p.code paddock_code,p.status paddock_status,p.version paddock_version from app.animals a left join app.paddocks p on p.tenant_id=a.tenant_id and p.farm_id=a.farm_id and p.id=a.paddock_id";}
 private static PaddockSummary map(java.sql.ResultSet r,int n)throws java.sql.SQLException{return new PaddockSummary(r.getObject("id",UUID.class),r.getString("name"),r.getString("code"),PaddockStatus.valueOf(r.getString("status")),r.getLong("version"),r.getLong("occupancy"));}
 private static HerdAnimalSummary animal(java.sql.ResultSet r,int n)throws java.sql.SQLException{UUID pid=r.getObject("paddock_id",UUID.class);PaddockSummary p=pid==null?null:new PaddockSummary(pid,r.getString("paddock_name"),r.getString("paddock_code"),PaddockStatus.valueOf(r.getString("paddock_status")),r.getLong("paddock_version"));return new HerdAnimalSummary(r.getObject("id",UUID.class),r.getString("identification"),r.getString("name"),HerdAnimalSex.valueOf(r.getString("sex")),r.getObject("birth_date",LocalDate.class),HerdAnimalStatus.valueOf(r.getString("status")),r.getLong("version"),p);}
 private static MapSqlParameterSource p(TenantId t,UUID f,UUID id){return new MapSqlParameterSource().addValue("tenantId",t.value()).addValue("farmId",f).addValue("id",id);} private static String escape(String s){return s.replace("\\","\\\\").replace("%","\\%").replace("_","\\_");}
}
