package com.gerenciadorrural.modules.herd.api;
import com.fasterxml.jackson.databind.*; import com.gerenciadorrural.infrastructure.database.*; import com.nimbusds.jose.*; import com.nimbusds.jose.crypto.MACSigner; import com.nimbusds.jwt.*; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.*; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.*; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.web.servlet.*; import java.sql.*; import java.time.*; import java.util.*; import java.util.concurrent.*; import static org.assertj.core.api.Assertions.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
@ActiveProfiles("test") @SpringBootTest(properties={"app.security.supabase.mode=HMAC","app.security.supabase.algorithm=HS256","app.security.supabase.issuer=https://auth.example.test/auth/v1","app.security.supabase.hmac-secret=test-only-hmac-key-with-at-least-32-bytes","app.security.supabase.audiences=authenticated","app.security.supabase.accepted-token-roles=authenticated"}) @AutoConfigureMockMvc
class HerdLifecycleConcurrentVerticalIntegrationTest extends SpringPostgresTestSupport {
 static final int N=5; static final String I="https://auth.example.test/auth/v1",S="test-only-hmac-key-with-at-least-32-bytes"; @Autowired MockMvc mvc; @Autowired ObjectMapper json; UUID user,tenant,farm; String token;
 @BeforeEach void seed()throws Exception{PostgresTestEnvironment.clearUsers();user=UUID.randomUUID();tenant=UUID.randomUUID();farm=UUID.randomUUID();UUID m=UUID.randomUUID();try(Connection c=PostgresTestEnvironment.adminConnection();var p=c.prepareStatement("insert into app.users(id,status)values(?,'ACTIVE');insert into app.organizations(id,name,status)values(?,'T','ACTIVE');insert into app.organization_memberships(id,tenant_id,user_id,role_key,status,farm_scope_mode)values(?,?,?,'OWNER','ACTIVE','SELECTED_FARMS');insert into app.farms(id,tenant_id,name,status)values(?,?,'F','ACTIVE');insert into app.membership_farm_scopes(tenant_id,membership_id,farm_id)values(?,?,?)")){p.setObject(1,user);p.setObject(2,tenant);p.setObject(3,m);p.setObject(4,tenant);p.setObject(5,user);p.setObject(6,farm);p.setObject(7,tenant);p.setObject(8,tenant);p.setObject(9,m);p.setObject(10,farm);p.executeUpdate();}token=token();}
 @Test void sameOperationSamePayloadFiveTimes()throws Exception{for(int i=0;i<N;i++){UUID a=create(i),op=UUID.randomUUID();List<R> r=pair(a,"sale",op,"Venda");statuses(r,200,200);assertState(a,"SOLD",1,1,op);assertWinner(a,r.getFirst());}}
 @Test void sameOperationDivergentPayloadFiveTimes()throws Exception{for(int i=0;i<N;i++){UUID a=create(i),op=UUID.randomUUID();List<R> r=pair(a,"sale",op,"A","sale",op,"B");statuses(r,200,409);assertThat(code(r.stream().filter(x->x.s==409).findFirst().orElseThrow())).isEqualTo("HERD_OPERATION_IDEMPOTENCY_CONFLICT");assertState(a,"SOLD",1,1,op);assertWinner(a,r.stream().filter(x->x.s==200).findFirst().orElseThrow());}}
 @Test void saleVsDeathFiveTimes()throws Exception{for(int i=0;i<N;i++){UUID a=create(i),x=UUID.randomUUID(),y=UUID.randomUUID();List<R> r=pair(a,"sale",x,"Venda","death",y,"Morte");statuses(r,200,409);assertThat(code(r.stream().filter(z->z.s==409).findFirst().orElseThrow())).isEqualTo("HERD_VERSION_CONFLICT");String status=status(a);assertThat(status).isIn("SOLD","DECEASED");assertThat(count(a)).isEqualTo(1);assertThat(version(a)).isEqualTo(1);assertWinner(a,r.stream().filter(z->z.s==200).findFirst().orElseThrow());}}
 @Test void operationFromAnotherAnimalConflictsEvenWhenVersionMatches()throws Exception{UUID a=create(1),b=create(2),op=UUID.randomUUID();assertThat(go(a,"sale",op,"Venda",new CyclicBarrier(1)).s).isEqualTo(200);try(Connection c=PostgresTestEnvironment.adminConnection();var p=c.prepareStatement("update app.animals set version=1 where id=?")){p.setObject(1,b);p.executeUpdate();}R result=go(b,"sale",op,"Venda",new CyclicBarrier(1));assertThat(result.s).isEqualTo(409);assertThat(code(result)).isEqualTo("HERD_OPERATION_IDEMPOTENCY_CONFLICT");assertThat(status(b)).isEqualTo("ACTIVE");assertThat(operation(b,op)).isZero();}
 UUID create(int i)throws Exception{UUID id=UUID.randomUUID();String b="{\"id\":\""+id+"\",\"identification\":\"L-"+UUID.randomUUID()+"\",\"sex\":\"FEMALE\"}";assertThat(call(post("/api/v1/herd/animals"),b).getResponse().getStatus()).isEqualTo(201);return id;}
 List<R> pair(UUID a,String t,UUID o,String n)throws Exception{return pair(a,t,o,n,t,o,n);} List<R> pair(UUID a,String t,UUID o,String n,String t2,UUID o2,String n2)throws Exception{ExecutorService e=Executors.newFixedThreadPool(2);CyclicBarrier b=new CyclicBarrier(2);try{Future<R>x=e.submit(()->go(a,t,o,n,b));Future<R>y=e.submit(()->go(a,t2,o2,n2,b));return List.of(x.get(20,TimeUnit.SECONDS),y.get(20,TimeUnit.SECONDS));}finally{e.shutdownNow();assertThat(e.awaitTermination(10,TimeUnit.SECONDS)).isTrue();}}
 R go(UUID a,String type,UUID op,String notes,CyclicBarrier b)throws Exception{b.await(10,TimeUnit.SECONDS);String body="{\"operationId\":\""+op+"\",\"expectedVersion\":0,\"occurredOn\":\"2026-09-08\",\"notes\":\""+notes+"\"}";MvcResult x=call(post("/api/v1/herd/animals/"+a+"/"+type),body);return new R(x.getResponse().getStatus(),x.getResponse().getContentAsString(),type,notes,op);}
 MvcResult call(org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder b,String body)throws Exception{return mvc.perform(b.contentType(MediaType.APPLICATION_JSON).header(HttpHeaders.AUTHORIZATION,"Bearer "+token).header("X-Organization-Id",tenant).header("X-Farm-Id",farm).content(body)).andReturn();} void statuses(List<R>r,int a,int b){assertThat(r).extracting(x->x.s).containsExactlyInAnyOrder(a,b);assertThat(r).allSatisfy(x->assertThat(x.s).isNotIn(500,503));}String code(R r)throws Exception{return json.readTree(r.b).path("code").asText();}
 void assertState(UUID a,String s,long v,long c,UUID o)throws Exception{assertThat(status(a)).isEqualTo(s);assertThat(version(a)).isEqualTo(v);assertThat(count(a)).isEqualTo(c);assertThat(operation(a,o)).isEqualTo(1);}void assertWinner(UUID animal,R winner)throws Exception{try(Connection c=PostgresTestEnvironment.adminConnection();var p=c.prepareStatement("select event_type,payload->>'notes' from app.animal_events where animal_id=? and operation_id=?")){p.setObject(1,animal);p.setObject(2,winner.op);var r=p.executeQuery();assertThat(r.next()).isTrue();assertThat(r.getString(1)).isEqualTo(winner.type.equals("sale")?"SOLD":"DECEASED");assertThat(r.getString(2)).isEqualTo(winner.notes);assertThat(r.next()).isFalse();}}String status(UUID a)throws Exception{return one("select status from app.animals where id=?",a);}long version(UUID a)throws Exception{return Long.parseLong(one("select version from app.animals where id=?",a));}long count(UUID a)throws Exception{return Long.parseLong(one("select count(*) from app.animal_events where animal_id=? and event_type in ('SOLD','DECEASED')",a));}long operation(UUID a,UUID o)throws Exception{return Long.parseLong(one("select count(*) from app.animal_events where animal_id=? and operation_id=?",a,o));}String one(String q,Object...v)throws Exception{try(Connection c=PostgresTestEnvironment.adminConnection();var p=c.prepareStatement(q)){for(int i=0;i<v.length;i++)p.setObject(i+1,v[i]);var r=p.executeQuery();r.next();return r.getString(1);}}
 String token()throws Exception{JWTClaimsSet c=new JWTClaimsSet.Builder().issuer(I).audience("authenticated").subject(user.toString()).claim("role","authenticated").issueTime(new java.util.Date()).expirationTime(java.util.Date.from(Instant.now().plusSeconds(300))).build();SignedJWT j=new SignedJWT(new JWSHeader(JWSAlgorithm.HS256),c);j.sign(new MACSigner(S.getBytes()));return j.serialize();} record R(int s,String b,String type,String notes,UUID op){}
}
