package com.gerenciadorrural.modules.herd.api;
import com.fasterxml.jackson.databind.*; import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule; import com.gerenciadorrural.modules.herd.application.*; import com.gerenciadorrural.modules.herd.domain.*; import com.gerenciadorrural.modules.organizations.api.ResolvedTenantContext; import com.gerenciadorrural.shared.tenancy.*; import org.junit.jupiter.api.*; import org.springframework.core.MethodParameter; import org.springframework.http.*; import org.springframework.http.converter.json.MappingJackson2HttpMessageConverter; import org.springframework.test.web.servlet.*; import org.springframework.web.bind.support.WebDataBinderFactory; import org.springframework.web.context.request.NativeWebRequest; import org.springframework.web.method.support.*; import java.time.*; import java.util.*; import static org.assertj.core.api.Assertions.assertThat; import static org.hamcrest.Matchers.containsString; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*; import static org.springframework.test.web.servlet.setup.MockMvcBuilders.standaloneSetup;
class HerdAnimalCreateControllerContractTest {
 private final TenantContext context=new TenantContext(new TenantId(UUID.randomUUID()),UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"OWNER","ALL_FARMS"); private CreateCurrentFarmAnimal create; private MockMvc mvc;
 @BeforeEach void setup(){create=mock(CreateCurrentFarmAnimal.class);ObjectMapper mapper=new ObjectMapper().registerModule(new JavaTimeModule()).disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);mvc=standaloneSetup(new HerdAnimalController(mock(ListCurrentFarmAnimals.class),create)).setControllerAdvice(new HerdAnimalExceptionHandler()).setCustomArgumentResolvers(new Resolver()).setMessageConverters(new MappingJackson2HttpMessageConverter(mapper)).build();}
 @Test void mapsCreatedAndDelegatesRawBody() throws Exception {UUID id=UUID.randomUUID();HerdAnimalSummary animal=new HerdAnimalSummary(id,"A-001","Brisa",HerdAnimalSex.FEMALE,LocalDate.of(2024,3,15),HerdAnimalStatus.ACTIVE,0);when(create.execute(eq(context),any())).thenReturn(new CreateCurrentFarmAnimalResult(CreateCurrentFarmAnimalResult.Outcome.CREATED,animal));mvc.perform(post("/api/v1/herd/animals").contentType(MediaType.APPLICATION_JSON).content("{\"id\":\""+id+"\",\"identification\":\"  A-001  \",\"name\":\"  Brisa  \",\"sex\":\"FEMALE\",\"birthDate\":\"2024-03-15\"}")).andExpect(status().isCreated()).andExpect(header().string(HttpHeaders.CACHE_CONTROL,containsString("no-store"))).andExpect(jsonPath("$.identification").value("A-001"));var cap=org.mockito.ArgumentCaptor.forClass(CreateCurrentFarmAnimalCommand.class);verify(create).execute(eq(context),cap.capture());assertThat(cap.getValue().identification()).isEqualTo("  A-001  ");}
 @Test void mapsReplayAndApplicationErrors() throws Exception {UUID id=UUID.randomUUID();when(create.execute(eq(context),any())).thenReturn(new CreateCurrentFarmAnimalResult(CreateCurrentFarmAnimalResult.Outcome.REPLAYED,new HerdAnimalSummary(id,"A",null,HerdAnimalSex.MALE,null,HerdAnimalStatus.ACTIVE,0)));mvc.perform(valid(id)).andExpect(status().isOk());for(var pair:List.of(new Object[]{new HerdAnimalCommandInvalidException(),400,"HERD_COMMAND_INVALID"},new Object[]{new HerdAnimalCreationForbiddenException(),403,"HERD_CREATION_FORBIDDEN"},new Object[]{new HerdAnimalIdentificationConflictException(),409,"HERD_IDENTIFICATION_CONFLICT"},new Object[]{new HerdAnimalIdempotencyConflictException(),409,"HERD_IDEMPOTENCY_CONFLICT"})){when(create.execute(eq(context),any())).thenThrow((RuntimeException)pair[0]);mvc.perform(valid(UUID.randomUUID())).andExpect(status().is((int)pair[1])).andExpect(jsonPath("$.code").value((String)pair[2]));}}
 @Test void rejectsMalformedAndInternalFields() throws Exception {for(String body:List.of("{", "{\"id\":\"bad\",\"identification\":\"A\",\"sex\":\"MALE\"}","{\"id\":\""+UUID.randomUUID()+"\",\"identification\":\"A\",\"sex\":\"OTHER\"}","{\"id\":\""+UUID.randomUUID()+"\",\"identification\":\"A\",\"sex\":\"MALE\",\"tenantId\":\"x\"}")){mvc.perform(post("/api/v1/herd/animals").contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isBadRequest()).andExpect(jsonPath("$.code").value("HERD_COMMAND_INVALID"));}verifyNoInteractions(create);}
 private org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder valid(UUID id){return post("/api/v1/herd/animals").contentType(MediaType.APPLICATION_JSON).content("{\"id\":\""+id+"\",\"identification\":\"A\",\"sex\":\"MALE\"}");}
 private final class Resolver implements HandlerMethodArgumentResolver {public boolean supportsParameter(MethodParameter p){return p.hasParameterAnnotation(ResolvedTenantContext.class)&&p.getParameterType()==TenantContext.class;}public Object resolveArgument(MethodParameter p,ModelAndViewContainer c,NativeWebRequest r,WebDataBinderFactory b){return context;}}
}
