package com.gerenciadorrural.modules.herd.application;

import com.gerenciadorrural.modules.herd.domain.*;
import com.gerenciadorrural.shared.tenancy.*;
import org.junit.jupiter.api.*;
import java.time.*; import java.util.*;
import static org.assertj.core.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;

class LifecycleCurrentFarmAnimalTest {
 private final TenantContext owner=new TenantContext(new TenantId(UUID.randomUUID()),UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"OWNER","ALL_FARMS");
 private final HerdAnimalProfileRepository animals=mock(HerdAnimalProfileRepository.class); private final AnimalEventRepository events=mock(AnimalEventRepository.class); private final TenantTransactionExecutor tx=mock(TenantTransactionExecutor.class); private final UUID id=UUID.randomUUID(); private final LifecycleCurrentFarmAnimal useCase=new LifecycleCurrentFarmAnimal(tx,animals,events,Clock.fixed(Instant.parse("2026-09-09T00:00:00Z"),ZoneOffset.UTC));
 @BeforeEach void setup(){doAnswer(x->((TenantTransactionalOperation<?>)x.getArgument(1)).execute()).when(tx).execute(any(),any(TenantTransactionalOperation.class));when(events.findByOperation(any(),any(),any())).thenReturn(Optional.empty());}
 private HerdAnimalSummary animal(HerdAnimalStatus status,long version){return new HerdAnimalSummary(id,"A-1","Brisa",HerdAnimalSex.FEMALE,LocalDate.of(2024,1,1),status,version);} private LifecycleCurrentFarmAnimalCommand command(long version){return new LifecycleCurrentFarmAnimalCommand(UUID.randomUUID(),version,LocalDate.of(2026,9,8)," nota ");}
 @Test void deathTransitionsAndRecordsNormalizedEvent(){when(animals.findByIdForCorrection(owner.tenantId(),owner.farmId(),id)).thenReturn(Optional.of(animal(HerdAnimalStatus.ACTIVE,0)));when(animals.updateStatus(any(),any(),any(),eq(0L),eq(HerdAnimalStatus.DECEASED))).thenReturn(Optional.of(animal(HerdAnimalStatus.DECEASED,1)));assertThat(useCase.death(owner,id,command(0L))).isEqualTo(animal(HerdAnimalStatus.DECEASED,1));verify(events).record(eq(owner.tenantId()),eq(owner.farmId()),eq(id),eq(AnimalEventType.DECEASED),any(),eq(owner.userId()),eq(LocalDate.of(2026,9,8)),eq(1L),argThat(x->x instanceof LifecycleEventDetails d&&d.notes().equals("nota")));}
 @Test void saleTransitionsAndRecordsEvent(){when(animals.findByIdForCorrection(owner.tenantId(),owner.farmId(),id)).thenReturn(Optional.of(animal(HerdAnimalStatus.ACTIVE,0)));when(animals.updateStatus(any(),any(),any(),eq(0L),eq(HerdAnimalStatus.SOLD))).thenReturn(Optional.of(animal(HerdAnimalStatus.SOLD,1)));assertThat(useCase.sale(owner,id,command(0L)).status()).isEqualTo(HerdAnimalStatus.SOLD);verify(events).record(eq(owner.tenantId()),eq(owner.farmId()),eq(id),eq(AnimalEventType.SOLD),any(),eq(owner.userId()),any(),eq(1L),any());}
 @Test void viewerAndOperatorSaleAreForbiddenBeforeTransaction(){TenantContext viewer=new TenantContext(owner.tenantId(),owner.userId(),owner.farmId(),owner.membershipId(),"VIEWER","ALL_FARMS");TenantContext operator=new TenantContext(owner.tenantId(),owner.userId(),owner.farmId(),owner.membershipId(),"OPERATOR","ALL_FARMS");assertThatThrownBy(()->useCase.death(viewer,id,command(0L))).isInstanceOf(HerdLifecycleForbiddenException.class);assertThatThrownBy(()->useCase.sale(operator,id,command(0L))).isInstanceOf(HerdLifecycleForbiddenException.class);verifyNoInteractions(tx,animals,events);}
 @Test void invalidDatesAreRejected(){assertThatThrownBy(()->useCase.death(owner,id,new LifecycleCurrentFarmAnimalCommand(UUID.randomUUID(),0L,LocalDate.of(2026,9,10),null))).isInstanceOf(HerdAnimalCommandInvalidException.class);when(animals.findByIdForCorrection(owner.tenantId(),owner.farmId(),id)).thenReturn(Optional.of(animal(HerdAnimalStatus.ACTIVE,0)));assertThatThrownBy(()->useCase.death(owner,id,new LifecycleCurrentFarmAnimalCommand(UUID.randomUUID(),0L,LocalDate.of(2023,1,1),null))).isInstanceOf(HerdAnimalCommandInvalidException.class);}
 @Test void replayPrecedesVersionAndTerminalState(){UUID operation=UUID.randomUUID();AnimalEvent e=new AnimalEvent(UUID.randomUUID(),id,AnimalEventType.SOLD,operation,owner.userId(),LocalDate.of(2026,9,8),Instant.now(),1,new LifecycleEventDetails("nota"));when(events.findByOperation(owner.tenantId(),owner.farmId(),operation)).thenReturn(Optional.of(e));when(animals.findById(owner.tenantId(),owner.farmId(),id)).thenReturn(Optional.of(animal(HerdAnimalStatus.SOLD,1)));assertThat(useCase.sale(owner,id,new LifecycleCurrentFarmAnimalCommand(operation,0L,LocalDate.of(2026,9,8),"nota"))).isEqualTo(animal(HerdAnimalStatus.SOLD,1));verify(animals,never()).findByIdForCorrection(any(),any(),any());}
 @Test void staleVersionPrecedesTerminalConflict(){when(animals.findByIdForCorrection(owner.tenantId(),owner.farmId(),id)).thenReturn(Optional.of(animal(HerdAnimalStatus.SOLD,1)));assertThatThrownBy(()->useCase.sale(owner,id,command(0L))).isInstanceOf(HerdAnimalVersionConflictException.class);}
 @Test void divergentReplayConflicts(){UUID operation=UUID.randomUUID();when(events.findByOperation(owner.tenantId(),owner.farmId(),operation)).thenReturn(Optional.of(new AnimalEvent(UUID.randomUUID(),id,AnimalEventType.SOLD,operation,owner.userId(),LocalDate.of(2026,9,8),Instant.now(),1,new LifecycleEventDetails(null))));assertThatThrownBy(()->useCase.sale(owner,id,new LifecycleCurrentFarmAnimalCommand(operation,0L,LocalDate.of(2026,9,8),"nota"))).isInstanceOf(HerdOperationIdempotencyConflictException.class);}
 @Test void operationFromAnotherAnimalConflictsBeforeItsLookup(){UUID operation=UUID.randomUUID(),other=UUID.randomUUID();when(events.findByOperation(owner.tenantId(),owner.farmId(),operation)).thenReturn(Optional.of(new AnimalEvent(UUID.randomUUID(),other,AnimalEventType.SOLD,operation,owner.userId(),LocalDate.of(2026,9,8),Instant.now(),1,new LifecycleEventDetails("nota"))));assertThatThrownBy(()->useCase.sale(owner,id,new LifecycleCurrentFarmAnimalCommand(operation,0L,LocalDate.of(2026,9,8),"nota"))).isInstanceOf(HerdOperationIdempotencyConflictException.class);verify(animals,never()).findById(any(),any(),any());}
}
