package com.gerenciadorrural.modules.herd.application;
import com.fasterxml.jackson.databind.ObjectMapper; import com.gerenciadorrural.modules.herd.domain.*; import com.gerenciadorrural.shared.tenancy.*; import org.junit.jupiter.api.*; import java.math.*; import java.time.*; import java.util.*; import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*;
class ManageHerdIntelligenceTest {TenantTransactionExecutor tx=mock(); HerdAnimalProfileRepository animals=mock(); HerdManagementRepository repo=mock(); AnimalEventRepository events=mock(); TenantContext c=new TenantContext(new TenantId(UUID.randomUUID()),UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"OPERATOR","ALL_FARMS"); ManageHerdIntelligence service;
 @BeforeEach void setup(){doAnswer(x->((TenantTransactionalOperation<?>)x.getArgument(1)).execute()).when(tx).execute(any(),org.mockito.ArgumentMatchers.<TenantTransactionalOperation<Object>>any());service=new ManageHerdIntelligence(tx,animals,repo,events,new ObjectMapper().findAndRegisterModules(),Clock.systemUTC());}
 @Test void rejectsDuplicateBatchAnimals(){UUID id=UUID.randomUUID();assertThatThrownBy(()->service.weights(c,UUID.randomUUID(),List.of(new ManageHerdIntelligence.WeightCommand(id,0,new BigDecimal("1"),LocalDate.now(),null),new ManageHerdIntelligence.WeightCommand(id,0,new BigDecimal("2"),LocalDate.now(),null)))).isInstanceOf(HerdAnimalCommandInvalidException.class);}
 @Test void rejectsInvalidWeight(){assertThatThrownBy(()->service.weights(c,UUID.randomUUID(),List.of(new ManageHerdIntelligence.WeightCommand(UUID.randomUUID(),0,BigDecimal.ZERO,LocalDate.now(),null)))).isInstanceOf(HerdAnimalCommandInvalidException.class);}
 @Test void rejectsWeightIntegerOverflowBeforeTransaction(){for(String value:List.of("100000","100000.0","1E+5")){assertThatThrownBy(()->service.weights(c,UUID.randomUUID(),List.of(new ManageHerdIntelligence.WeightCommand(UUID.randomUUID(),0,new BigDecimal(value),LocalDate.now(),null)))).isInstanceOf(HerdAnimalCommandInvalidException.class);}verifyNoInteractions(tx,animals,repo,events);}
 @Test void rejectsNullBatchIdentifiersBeforeSorting(){var valid=new ManageHerdIntelligence.WeightCommand(UUID.randomUUID(),0,BigDecimal.ONE,LocalDate.now(),null);var invalid=new ManageHerdIntelligence.WeightCommand(null,0,BigDecimal.ONE,LocalDate.now(),null);assertThatThrownBy(()->service.weights(c,UUID.randomUUID(),List.of(valid,invalid))).isInstanceOf(HerdAnimalCommandInvalidException.class);assertThatThrownBy(()->service.health(c,UUID.randomUUID(),HealthTreatmentType.VACCINATION,null,LocalDate.now(),null,null,null,null,List.of(new ManageHerdIntelligence.BasicAnimalCommand(UUID.randomUUID(),0),new ManageHerdIntelligence.BasicAnimalCommand(null,0)))).isInstanceOf(HerdAnimalCommandInvalidException.class);verifyNoInteractions(tx,animals,repo,events);}
}
