package com.gerenciadorrural.modules.platform.api;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.gerenciadorrural.modules.platform.application.PlatformAdministrationService;
import com.gerenciadorrural.modules.platform.domain.PlatformAdministrationRepository.*;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.http.*;
import org.springframework.web.bind.annotation.*;
import java.util.*;

@RestController @RequestMapping("/api/v1")
public class PlatformAdministrationController {
 private final PlatformAdministrationService service; public PlatformAdministrationController(PlatformAdministrationService service){this.service=service;}
 @PostMapping("/organizations") public ResponseEntity<Organization> create(@Valid @RequestBody OrganizationCreate r){return ResponseEntity.status(HttpStatus.CREATED).cacheControl(CacheControl.noStore()).body(service.createOrganization(r.id(),name(r.name())));}
 @GetMapping("/organizations/{organizationId}") public Organization get(@PathVariable UUID organizationId){return service.organization(organizationId);}
 @PatchMapping("/organizations/{organizationId}") public Organization patch(@PathVariable UUID organizationId,@Valid @RequestBody OrganizationPatch r){return service.updateOrganization(organizationId,r.name()==null?null:name(r.name()),r.status(),r.expectedVersion());}
 @GetMapping("/organizations/{organizationId}/farms") public List<Farm> farms(@PathVariable UUID organizationId){return service.farms(organizationId);}
 @PostMapping("/organizations/{organizationId}/farms") public ResponseEntity<Farm> createFarm(@PathVariable UUID organizationId,@Valid @RequestBody FarmCreate r){return ResponseEntity.status(HttpStatus.CREATED).body(service.createFarm(organizationId,r.id(),name(r.name())));}
 @GetMapping("/organizations/{organizationId}/farms/{farmId}") public Farm farm(@PathVariable UUID organizationId,@PathVariable UUID farmId){return service.farm(organizationId,farmId);}
 @PatchMapping("/organizations/{organizationId}/farms/{farmId}") public Farm patchFarm(@PathVariable UUID organizationId,@PathVariable UUID farmId,@Valid @RequestBody FarmPatch r){return service.updateFarm(organizationId,farmId,r.name()==null?null:name(r.name()),r.status(),r.expectedVersion());}
 @GetMapping("/organizations/{organizationId}/members") public List<Member> members(@PathVariable UUID organizationId,@RequestParam(defaultValue="0") @PositiveOrZero int page,@RequestParam(defaultValue="50") @Min(1) @Max(100) int size){return service.members(organizationId,page,size);}
 @PostMapping("/organizations/{organizationId}/members") public ResponseEntity<Member> addMember(@PathVariable UUID organizationId,@Valid @RequestBody MemberCreate r){return ResponseEntity.status(HttpStatus.CREATED).body(service.addMember(organizationId,r.userId(),r.role(),r.farmScopeMode(),r.farmIds()==null?List.of():r.farmIds()));}
 @PatchMapping("/organizations/{organizationId}/members/{membershipId}") public Member patchMember(@PathVariable UUID organizationId,@PathVariable UUID membershipId,@Valid @RequestBody MemberPatch r){return service.updateMember(organizationId,membershipId,r.role(),r.farmScopeMode(),r.farmIds()==null?List.of():r.farmIds(),r.expectedVersion());}
 @DeleteMapping("/organizations/{organizationId}/members/{membershipId}") @ResponseStatus(HttpStatus.NO_CONTENT) public void revokeMember(@PathVariable UUID organizationId,@PathVariable UUID membershipId){service.revokeMember(organizationId,membershipId);}
 @PostMapping("/organizations/{organizationId}/invitations") public ResponseEntity<InvitationCreated> invite(@PathVariable UUID organizationId,@Valid @RequestBody InvitationCreate r){var result=service.invite(organizationId,email(r.email()),r.role(),r.farmScopeMode(),r.farmIds()==null?List.of():r.farmIds());return ResponseEntity.status(HttpStatus.CREATED).cacheControl(CacheControl.noStore()).body(new InvitationCreated(result.invitation(),result.token()));}
 @GetMapping("/organizations/{organizationId}/invitations") public List<Invitation> invitations(@PathVariable UUID organizationId,@RequestParam(required=false) String status,@RequestParam(defaultValue="0") @PositiveOrZero int page,@RequestParam(defaultValue="50") @Min(1) @Max(100) int size){return service.invitations(organizationId,status,page,size);}
 @PostMapping("/organizations/{organizationId}/invitations/{invitationId}/revocation") @ResponseStatus(HttpStatus.NO_CONTENT) public void revokeInvitation(@PathVariable UUID organizationId,@PathVariable UUID invitationId){service.revokeInvitation(organizationId,invitationId);}
 @PostMapping("/invitations/{token}/accept") @ResponseStatus(HttpStatus.NO_CONTENT) public void accept(@PathVariable String token){service.accept(token);}
 @GetMapping("/organizations/{organizationId}/audit") public List<AuditEvent> audit(@PathVariable UUID organizationId,@RequestParam(required=false) String eventType,@RequestParam(required=false) UUID farmId,@RequestParam(defaultValue="0") @PositiveOrZero int page,@RequestParam(defaultValue="50") @Min(1) @Max(100) int size){return service.audit(organizationId,eventType,farmId,page,size);}
 private static String name(String value){String x=value.trim();if(x.indexOf('\0')>=0||x.codePointCount(0,x.length())>160)throw new IllegalArgumentException("Nome inválido");return x;} private static String email(String value){String x=value.trim().toLowerCase(Locale.ROOT);if(x.indexOf('\0')>=0||x.length()>320||!x.matches("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$"))throw new IllegalArgumentException("E-mail inválido");return x;}
 @JsonIgnoreProperties(ignoreUnknown=false) public record OrganizationCreate(@NotNull UUID id,@NotBlank String name){} @JsonIgnoreProperties(ignoreUnknown=false) public record OrganizationPatch(String name,String status,@NotNull @PositiveOrZero Long expectedVersion){} @JsonIgnoreProperties(ignoreUnknown=false) public record FarmCreate(@NotNull UUID id,@NotBlank String name){} @JsonIgnoreProperties(ignoreUnknown=false) public record FarmPatch(String name,String status,@NotNull @PositiveOrZero Long expectedVersion){} @JsonIgnoreProperties(ignoreUnknown=false) public record MemberCreate(@NotNull UUID userId,@NotBlank String role,@NotBlank String farmScopeMode,List<UUID> farmIds){} @JsonIgnoreProperties(ignoreUnknown=false) public record MemberPatch(String role,String farmScopeMode,List<UUID> farmIds,@NotNull @PositiveOrZero Long expectedVersion){} @JsonIgnoreProperties(ignoreUnknown=false) public record InvitationCreate(@NotBlank String email,@NotBlank String role,@NotBlank String farmScopeMode,List<UUID> farmIds){} public record InvitationCreated(Invitation invitation,String token){}
}
