springdoc:
  api-docs:
    enabled: ${OPENAPI_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:false}

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
