package com.gerenciadorrural.modules.platform.infrastructure;

import com.gerenciadorrural.modules.platform.domain.PlatformAdministrationRepository;
import com.gerenciadorrural.shared.infrastructure.database.TransactionalCurrentUserContext;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;
import java.time.Instant;
import java.time.OffsetDateTime;
import java.util.*;

@Repository
public class JdbcPlatformAdministrationRepository implements PlatformAdministrationRepository {
 private final NamedParameterJdbcTemplate jdbc; private final TransactionalCurrentUserContext context;
 public JdbcPlatformAdministrationRepository(NamedParameterJdbcTemplate jdbc, TransactionalCurrentUserContext context){this.jdbc=jdbc;this.context=context;}
 private void access(UUID user, UUID organization){context.configure(user); jdbc.queryForObject("select set_config('app.current_tenant_id',:tenant,true)",new MapSqlParameterSource("tenant",organization.toString()),String.class);}
 public void lockOrganizationAdministration(UUID actor,UUID organization){access(actor,organization);jdbc.query("select app.lock_organization_administration(:o)",p("o",organization),(r,n)->null);}
 private MapSqlParameterSource p(Object... a){var p=new MapSqlParameterSource();for(int i=0;i<a.length;i+=2)p.addValue((String)a[i],a[i+1]);return p;}
 public Organization createOrganization(UUID actor,UUID id,String name){context.configure(actor);return jdbc.queryForObject("select * from app.create_organization_for_current_user(:id,:name)",p("id",id,"name",name),(r,n)->org(r));}
 public Optional<Membership> membership(UUID actor,UUID o){access(actor,o);return jdbc.query("select id,user_id,role_key,status,farm_scope_mode,version from app.organization_memberships where tenant_id=:o and user_id=:u and status='ACTIVE'",p("o",o,"u",actor),(r,n)->new Membership(r.getObject("id",UUID.class),r.getObject("user_id",UUID.class),r.getString("role_key"),r.getString("status"),r.getString("farm_scope_mode"),r.getLong("version"))).stream().findFirst();}
 public Optional<Organization> organization(UUID a,UUID o){access(a,o);return jdbc.query("select id,name,status,version from app.organizations where id=:o",p("o",o),(r,n)->org(r)).stream().findFirst();}
 public Optional<Organization> updateOrganization(UUID a,UUID o,String name,String status,long v){access(a,o);if(name==null&&status==null)return jdbc.query("select id,name,status,version from app.organizations where id=:o and version=:v",p("o",o,"v",v),(r,n)->org(r)).stream().findFirst();var updated=jdbc.query("update app.organizations set name=coalesce(:name,name),status=coalesce(:status,status),version=version+1,updated_at=current_timestamp where id=:o and version=:v and (name is distinct from coalesce(:name,name) or status is distinct from coalesce(:status,status)) returning id,name,status,version",p("o",o,"name",name,"status",status,"v",v),(r,n)->org(r));if(!updated.isEmpty())event(o,null,a,null,"ORGANIZATION_CORRECTED","{}");return updated.stream().findFirst();}
 public List<Farm> farms(UUID a,UUID o){access(a,o);return jdbc.query("select id,tenant_id,name,status,version from app.farms where tenant_id=:o order by name,id",p("o",o),(r,n)->farm(r));}
 public Optional<Farm> farm(UUID a,UUID o,UUID f){access(a,o);return jdbc.query("select id,tenant_id,name,status,version from app.farms where tenant_id=:o and id=:f",p("o",o,"f",f),(r,n)->farm(r)).stream().findFirst();}
 public Farm createFarm(UUID a,UUID o,UUID id,String name){access(a,o);var x=jdbc.queryForObject("insert into app.farms(id,tenant_id,name,status) values(:id,:o,:n,'ACTIVE') returning id,tenant_id,name,status,version",p("id",id,"o",o,"n",name),(r,n)->farm(r));event(o,null,a,null,"FARM_CREATED","{\"name\":\""+json(name)+"\"}");return x;}
 public Optional<Farm> updateFarm(UUID a,UUID o,UUID f,String name,String status,long v){access(a,o);if(name==null&&status==null)return jdbc.query("select id,tenant_id,name,status,version from app.farms where tenant_id=:o and id=:f and version=:v",p("o",o,"f",f,"v",v),(x,n)->farm(x)).stream().findFirst();var r=jdbc.query("update app.farms set name=coalesce(:n,name),status=coalesce(:s,status),version=version+1,updated_at=current_timestamp where tenant_id=:o and id=:f and version=:v and (name is distinct from coalesce(:n,name) or status is distinct from coalesce(:s,status)) returning id,tenant_id,name,status,version",p("o",o,"f",f,"n",name,"s",status,"v",v),(x,n)->farm(x));if(!r.isEmpty())event(o,f,a,null,"FARM_CORRECTED","{}");return r.stream().findFirst();}
 public List<Member> members(UUID a,UUID o,int off,int size){access(a,o);return jdbc.query("select m.id,m.user_id,u.display_name,u.email,m.role_key,m.status,m.farm_scope_mode,m.version,m.created_at,array_remove(array_agg(s.farm_id),null) farms from app.organization_memberships m join app.users u on u.id=m.user_id left join app.membership_farm_scopes s on s.tenant_id=m.tenant_id and s.membership_id=m.id where m.tenant_id=:o group by m.id,u.id order by m.created_at,m.id offset :off limit :size",p("o",o,"off",off,"size",size),(r,n)->member(r));}
 public Optional<Member> addMember(UUID a,UUID o,UUID u,String role,String scope,List<UUID> farms){access(a,o);UUID id=UUID.randomUUID();try{int n=jdbc.update("insert into app.organization_memberships(id,tenant_id,user_id,role_key,status,farm_scope_mode) select :id,:o,:u,:r,'ACTIVE',:s where exists(select 1 from app.users where id=:u and status='ACTIVE')",p("id",id,"o",o,"u",u,"r",role,"s",scope));if(n==0)return Optional.empty();for(UUID f:farms)jdbc.update("insert into app.membership_farm_scopes(tenant_id,membership_id,farm_id) values(:o,:id,:f)",p("o",o,"id",id,"f",f));event(o,null,a,u,"MEMBER_ADDED","{}");return member(a,o,id);}catch(org.springframework.dao.DuplicateKeyException e){return Optional.empty();}}
 public Optional<Member> member(UUID a,UUID o,UUID id){access(a,o);return members(a,o,0,100).stream().filter(x->x.membershipId().equals(id)).findFirst();}
 public Optional<Member> updateMember(UUID a,UUID o,UUID id,String role,String scope,List<UUID> farms,long v){access(a,o);if(role==null&&scope==null)return member(a,o,id).filter(x->x.version()==v);var rows=jdbc.query("update app.organization_memberships set role_key=coalesce(:r,role_key),farm_scope_mode=coalesce(:s,farm_scope_mode),version=version+1,updated_at=current_timestamp where tenant_id=:o and id=:id and version=:v returning id",p("o",o,"id",id,"r",role,"s",scope,"v",v),(r,n)->r.getObject("id",UUID.class));if(rows.isEmpty())return Optional.empty();if(scope!=null){jdbc.update("delete from app.membership_farm_scopes where tenant_id=:o and membership_id=:id",p("o",o,"id",id));for(UUID f:farms)jdbc.update("insert into app.membership_farm_scopes(tenant_id,membership_id,farm_id) values(:o,:id,:f)",p("o",o,"id",id,"f",f));}event(o,null,a,member(a,o,id).map(Member::userId).orElse(null),role!=null?"MEMBER_ROLE_CHANGED":"MEMBER_SCOPE_CHANGED","{}");return member(a,o,id);}
 public boolean revokeMember(UUID a,UUID o,UUID id){access(a,o);int n=jdbc.update("update app.organization_memberships set status='REVOKED',version=version+1,updated_at=current_timestamp where tenant_id=:o and id=:id and status='ACTIVE'",p("o",o,"id",id));if(n==1)event(o,null,a,null,"MEMBER_REVOKED","{}");return n==1;}
 public Invitation createInvitation(UUID a,UUID o,String email,String role,String scope,List<UUID> farms,String hash,Instant expiry){access(a,o);UUID id=UUID.randomUUID();jdbc.update("insert into app.organization_invitations(id,organization_id,invited_email,normalized_email,role_key,farm_scope_mode,status,token_hash,invited_by_user_id,expires_at) values(:id,:o,:e,:e,:r,:s,'PENDING',:h,:a,:x)",p("id",id,"o",o,"e",email,"r",role,"s",scope,"h",hash,"a",a,"x",OffsetDateTime.ofInstant(expiry,java.time.ZoneOffset.UTC)));for(UUID f:farms)jdbc.update("insert into app.organization_invitation_farm_scopes(invitation_id,farm_id) values(:i,:f)",p("i",id,"f",f));event(o,null,a,null,"INVITATION_CREATED","{}");return new Invitation(id,email,role,scope,"PENDING",expiry,Instant.now());}
 public List<Invitation> invitations(UUID a,UUID o,String st,int off,int size){access(a,o);return jdbc.query("select id,invited_email,role_key,farm_scope_mode,case when status='PENDING' and expires_at<=current_timestamp then 'EXPIRED' else status end status,expires_at,created_at from app.organization_invitations where organization_id=:o and (:s is null or status=:s) order by created_at desc,id desc offset :off limit :size",p("o",o,"s",st,"off",off,"size",size),(r,n)->invite(r));}
 public Optional<Invitation> invitationByToken(UUID a,String h){return Optional.empty();}
 public boolean acceptInvitation(UUID a,String hash){context.configure(a);Boolean x=jdbc.queryForObject("select app.accept_organization_invitation(:h)",p("h",hash),Boolean.class);return Boolean.TRUE.equals(x);}
 public boolean revokeInvitation(UUID a,UUID o,UUID id){access(a,o);int n=jdbc.update("update app.organization_invitations set status='REVOKED',revoked_at=current_timestamp where id=:id and organization_id=:o and status='PENDING'",p("id",id,"o",o));if(n==1)event(o,null,a,null,"INVITATION_REVOKED","{}");return n==1;}
 public List<AuditEvent> audit(UUID a,UUID o,String type,UUID f,int off,int size){access(a,o);return jdbc.query("select id,farm_id,actor_user_id,target_user_id,event_type,details::text,recorded_at from app.platform_admin_events where organization_id=:o and (:t is null or event_type=:t) and (:f is null or farm_id=:f) order by recorded_at desc,id desc offset :off limit :size",p("o",o,"t",type,"f",f,"off",off,"size",size),(r,n)->new AuditEvent(r.getObject("id",UUID.class),r.getObject("farm_id",UUID.class),r.getObject("actor_user_id",UUID.class),r.getObject("target_user_id",UUID.class),r.getString("event_type"),r.getString("details"),r.getObject("recorded_at",OffsetDateTime.class).toInstant()));}
 private void event(UUID o,UUID f,UUID a,UUID t,String type,String details){jdbc.update("insert into app.platform_admin_events(id,organization_id,farm_id,actor_user_id,target_user_id,event_type,details) values(:id,:o,:f,:a,:t,:e,cast(:d as jsonb))",p("id",UUID.randomUUID(),"o",o,"f",f,"a",a,"t",t,"e",type,"d",details));}
 private static Organization org(java.sql.ResultSet r)throws java.sql.SQLException{return new Organization(r.getObject("id",UUID.class),r.getString("name"),r.getString("status"),r.getLong("version"));} private static Farm farm(java.sql.ResultSet r)throws java.sql.SQLException{return new Farm(r.getObject("id",UUID.class),r.getObject("tenant_id",UUID.class),r.getString("name"),r.getString("status"),r.getLong("version"));}
 private static Member member(java.sql.ResultSet r)throws java.sql.SQLException{var arr=r.getArray("farms");UUID[] fs=arr==null?new UUID[0]:(UUID[])arr.getArray();return new Member(r.getObject("id",UUID.class),r.getObject("user_id",UUID.class),r.getString("display_name"),r.getString("email"),r.getString("role_key"),r.getString("status"),r.getString("farm_scope_mode"),List.of(fs),r.getLong("version"),r.getObject("created_at",OffsetDateTime.class).toInstant());} private static Invitation invite(java.sql.ResultSet r)throws java.sql.SQLException{return new Invitation(r.getObject("id",UUID.class),r.getString("invited_email"),r.getString("role_key"),r.getString("farm_scope_mode"),r.getString("status"),r.getObject("expires_at",OffsetDateTime.class).toInstant(),r.getObject("created_at",OffsetDateTime.class).toInstant());} private static String json(String v){return v.replace("\\","\\\\").replace("\"","\\\"");}
}
