package com.gerenciadorrural.modules.finance.api;

import com.gerenciadorrural.infrastructure.database.PostgresTestEnvironment;
import com.nimbusds.jose.*; import com.nimbusds.jose.crypto.MACSigner; import com.nimbusds.jwt.*;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.*; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.*; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.web.servlet.*;
import java.sql.Connection; import java.sql.ResultSet; import java.sql.Statement; import java.time.*; import java.util.*; import java.util.concurrent.*;
import static org.assertj.core.api.Assertions.assertThat; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;

@ActiveProfiles("test") @SpringBootTest(properties={"app.security.supabase.mode=HMAC","app.security.supabase.algorithm=HS256","app.security.supabase.issuer=https://auth.example.test/auth/v1","app.security.supabase.hmac-secret=test-only-hmac-key-with-at-least-32-bytes","app.security.supabase.audiences=authenticated","app.security.supabase.accepted-token-roles=authenticated"}) @AutoConfigureMockMvc
class FinanceConcurrencyIntegrationTest extends com.gerenciadorrural.infrastructure.database.SpringPostgresTestSupport {
 private static final String ISSUER="https://auth.example.test/auth/v1",SECRET="test-only-hmac-key-with-at-least-32-bytes"; @Autowired MockMvc mvc; UUID user,tenant,farm,category; String token;
 @BeforeEach void seed()throws Exception{PostgresTestEnvironment.clearUsers();user=UUID.randomUUID();tenant=UUID.randomUUID();farm=UUID.randomUUID();category=UUID.randomUUID();try(Connection c=PostgresTestEnvironment.adminConnection();Statement s=c.createStatement()){s.execute("insert into app.users(id,status) values('"+user+"','ACTIVE')");s.execute("insert into app.organizations(id,name,status) values('"+tenant+"','T','ACTIVE')");s.execute("insert into app.farms(id,tenant_id,name,status) values('"+farm+"','"+tenant+"','F','ACTIVE')");s.execute("insert into app.financial_categories(id,tenant_id,name,kind,status) values('"+category+"','"+tenant+"','C','BOTH','ACTIVE')");UUID m=UUID.randomUUID();s.execute("insert into app.organization_memberships(id,tenant_id,user_id,role_key,status,farm_scope_mode) values('"+m+"','"+tenant+"','"+user+"','OWNER','ACTIVE','SELECTED_FARMS')");s.execute("insert into app.membership_farm_scopes(tenant_id,membership_id,farm_id) values('"+tenant+"','"+m+"','"+farm+"')");}token=token(user);}
 @Test void serializesConcurrentCreateReplaysAndRejectsDivergentPayloads()throws Exception{for(int i=0;i<5;i++){UUID op=UUID.randomUUID();List<Integer> same=concurrent(body(op,"100.0"),body(op,"100.00"));assertThat(same).containsExactlyInAnyOrder(201,201);assertThat(count("financial_entries","operation_id",op)).isEqualTo(1);assertThat(count("financial_entry_events","operation_id",op)).isEqualTo(1);UUID divergent=UUID.randomUUID();List<Integer> result=concurrent(body(divergent,"101"),body(divergent,"102"));assertThat(result).contains(201,409);assertThat(count("financial_entries","operation_id",divergent)).isEqualTo(1);}}
 @Test void concurrentTerminalTransitionsHaveOneWinnerAndSameOperationReplays()throws Exception{for(int i=0;i<5;i++){UUID create=UUID.randomUUID();assertThat(call(body(create,"100"))).isEqualTo(201);UUID entry=entry(create);UUID same=UUID.randomUUID();List<Integer> replay=concurrent(settle(entry,same,"2026-09-10"),settle(entry,same,"2026-09-10"));assertThat(replay).containsExactlyInAnyOrder(200,200);assertThat(events(entry,"SETTLED")).isEqualTo(1);assertThat(version(entry)).isEqualTo(1);assertThat(status(entry)).isEqualTo("SETTLED");UUID otherCreate=UUID.randomUUID();assertThat(call(body(otherCreate,"100"))).isEqualTo(201);UUID other=entry(otherCreate);List<Integer> race=concurrent(settle(other,UUID.randomUUID(),"2026-09-10"),cancel(other,UUID.randomUUID(),"Motivo"));assertThat(race).containsExactlyInAnyOrder(200,409);assertThat(events(other,"SETTLED")+events(other,"CANCELLED")).isEqualTo(1);assertThat(version(other)).isEqualTo(1);}}
 @Test void concurrentPatchAndTerminalRejectStaleMutation()throws Exception{UUID create=UUID.randomUUID();assertThat(call(body(create,"100"))).isEqualTo(201);UUID entry=entry(create);List<Integer> patchRace=concurrent(patch(entry,"{\"expectedVersion\":0,\"description\":\"A\",\"descriptionSet\":true}"),patch(entry,"{\"expectedVersion\":0,\"amount\":101,\"amountSet\":true}"));assertThat(patchRace).containsExactlyInAnyOrder(200,409);assertThat(version(entry)).isEqualTo(1);assertThat(events(entry,"CORRECTED")).isEqualTo(1);UUID terminalCreate=UUID.randomUUID();assertThat(call(body(terminalCreate,"100"))).isEqualTo(201);UUID terminal=entry(terminalCreate);List<Integer> terminalRace=concurrent(patch(terminal,"{\"expectedVersion\":0,\"description\":\"A\",\"descriptionSet\":true}"),cancel(terminal,UUID.randomUUID(),"Motivo"));assertThat(terminalRace).containsExactlyInAnyOrder(200,409);assertThat(version(terminal)).isEqualTo(1);}
 private UUID entry(UUID op)throws Exception{try(Connection c=PostgresTestEnvironment.adminConnection();Statement s=c.createStatement();ResultSet r=s.executeQuery("select id from app.financial_entries where operation_id='"+op+"'")){assertThat(r.next()).isTrue();return r.getObject(1,UUID.class);}}private String settle(UUID id,UUID op,String date){return "SETTLE|"+id+"|{\"operationId\":\""+op+"\",\"expectedVersion\":0,\"settledOn\":\""+date+"\"}";}private String cancel(UUID id,UUID op,String reason){return "CANCEL|"+id+"|{\"operationId\":\""+op+"\",\"expectedVersion\":0,\"reason\":\""+reason+"\"}";}private String patch(UUID id,String json){return "PATCH|"+id+"|"+json;}private int events(UUID id,String type)throws Exception{return scalar("select count(*) from app.financial_entry_events where entry_id='"+id+"' and event_type='"+type+"'");}private int version(UUID id)throws Exception{return scalar("select version from app.financial_entries where id='"+id+"'");}private String status(UUID id)throws Exception{try(Connection c=PostgresTestEnvironment.adminConnection();Statement s=c.createStatement();ResultSet r=s.executeQuery("select status from app.financial_entries where id='"+id+"'")){r.next();return r.getString(1);}}private int scalar(String q)throws Exception{try(Connection c=PostgresTestEnvironment.adminConnection();Statement s=c.createStatement();ResultSet r=s.executeQuery(q)){r.next();return r.getInt(1);}}
 private List<Integer> concurrent(String a,String b)throws Exception{ExecutorService e=Executors.newFixedThreadPool(2);CyclicBarrier gate=new CyclicBarrier(2);try{Future<Integer>x=e.submit(()->{gate.await(10,TimeUnit.SECONDS);return call(a);}),y=e.submit(()->{gate.await(10,TimeUnit.SECONDS);return call(b);});return List.of(x.get(20,TimeUnit.SECONDS),y.get(20,TimeUnit.SECONDS));}finally{e.shutdownNow();}}private static org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder patch(String url){return org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch(url);}
 private String body(UUID op,String amount){return "{\"operationId\":\""+op+"\",\"type\":\"INCOME\",\"categoryId\":\""+category+"\",\"description\":\"Receita\",\"amount\":"+amount+",\"dueOn\":\"2026-09-10\"}";}private int call(String body)throws Exception{String[] parts=body.split("\\|",3);var request=post("/api/v1/finance/entries");String content=body;if(parts.length==3){UUID id=UUID.fromString(parts[1]);content=parts[2];request=switch(parts[0]){case "SETTLE"->post("/api/v1/finance/entries/"+id+"/settlement");case "CANCEL"->post("/api/v1/finance/entries/"+id+"/cancellation");case "PATCH"->patch("/api/v1/finance/entries/"+id);default->request;};}return mvc.perform(request.header(HttpHeaders.AUTHORIZATION,"Bearer "+token).header("X-Organization-Id",tenant).header("X-Farm-Id",farm).contentType(MediaType.APPLICATION_JSON).content(content)).andReturn().getResponse().getStatus();}private int count(String table,String column,UUID id)throws Exception{try(Connection c=PostgresTestEnvironment.adminConnection();Statement s=c.createStatement();ResultSet r=s.executeQuery("select count(*) from app."+table+" where "+column+"='"+id+"'")){r.next();return r.getInt(1);}}private static String token(UUID id)throws Exception{JWTClaimsSet c=new JWTClaimsSet.Builder().issuer(ISSUER).audience("authenticated").subject(id.toString()).claim("role","authenticated").issueTime(new Date()).expirationTime(Date.from(Instant.now().plusSeconds(300))).build();SignedJWT j=new SignedJWT(new JWSHeader(JWSAlgorithm.HS256),c);j.sign(new MACSigner(SECRET.getBytes()));return j.serialize();}}
