package com.gerenciadorrural.modules.herd.api;
import com.gerenciadorrural.modules.herd.application.*; import com.gerenciadorrural.shared.api.error.ApiErrorResponse; import com.gerenciadorrural.shared.observability.RequestContextFilter; import com.gerenciadorrural.shared.tenancy.TenantTransactionInfrastructureException; import jakarta.servlet.http.HttpServletRequest; import java.time.Instant; import java.util.List; import org.springframework.core.annotation.*; import org.springframework.core.Ordered; import org.springframework.dao.*; import org.springframework.http.*; import org.springframework.transaction.TransactionException; import org.springframework.web.bind.annotation.*; import org.springframework.http.converter.HttpMessageNotReadableException; import org.springframework.web.method.annotation.MethodArgumentTypeMismatchException;
@Order(Ordered.HIGHEST_PRECEDENCE) @RestControllerAdvice(assignableTypes={HerdAnimalController.class,PaddockController.class,HerdMovementController.class,PaddockMovementLogController.class,HerdTransferController.class,HerdIntelligenceController.class,HerdReproductionController.class,HerdPlannerController.class,HerdAgendaController.class,HerdReportController.class,HerdDashboardController.class}) class HerdAnimalExceptionHandler {
 @ExceptionHandler({HerdAnimalQueryException.class,HerdPlannerExceptions.QueryInvalid.class,HerdReportQueryInvalidException.class,HerdDashboardQueryInvalidException.class,MethodArgumentTypeMismatchException.class}) ResponseEntity<ApiErrorResponse> query(HttpServletRequest r){return error(HttpStatus.BAD_REQUEST,"HERD_QUERY_INVALID","A consulta de rebanho é inválida",r);}
 @ExceptionHandler({HerdAnimalCommandInvalidException.class,HttpMessageNotReadableException.class}) ResponseEntity<ApiErrorResponse> invalid(HttpServletRequest r){return error(HttpStatus.BAD_REQUEST,"HERD_COMMAND_INVALID","O comando de rebanho é inválido",r);}
 @ExceptionHandler(HerdAnimalCreationForbiddenException.class) ResponseEntity<ApiErrorResponse> creation(HttpServletRequest r){return error(HttpStatus.FORBIDDEN,"HERD_CREATION_FORBIDDEN","A criação de animais não é permitida",r);}
 @ExceptionHandler(HerdAnimalCorrectionForbiddenException.class) ResponseEntity<ApiErrorResponse> correction(HttpServletRequest r){return error(HttpStatus.FORBIDDEN,"HERD_CORRECTION_FORBIDDEN","A correção de animais não é permitida",r);}
 @ExceptionHandler(HerdLifecycleForbiddenException.class) ResponseEntity<ApiErrorResponse> lifecycleForbidden(HttpServletRequest r){return error(HttpStatus.FORBIDDEN,"HERD_LIFECYCLE_FORBIDDEN","A operação de ciclo de vida não é permitida",r);}
 @ExceptionHandler(HerdPaddockForbiddenException.class) ResponseEntity<ApiErrorResponse> paddockForbidden(HttpServletRequest r){return error(HttpStatus.FORBIDDEN,"HERD_PADDOCK_FORBIDDEN","A alteração de piquete não é permitida",r);}
 @ExceptionHandler(HerdMovementForbiddenException.class) ResponseEntity<ApiErrorResponse> movementForbidden(HttpServletRequest r){return error(HttpStatus.FORBIDDEN,"HERD_MOVEMENT_FORBIDDEN","A movimentação de animais não é permitida",r);}
 @ExceptionHandler(HerdTransferForbiddenException.class) ResponseEntity<ApiErrorResponse> transferForbidden(HttpServletRequest r){return error(HttpStatus.FORBIDDEN,"HERD_TRANSFER_FORBIDDEN","A transferência entre fazendas não é permitida",r);}
 @ExceptionHandler(HerdAnimalNotFoundException.class) ResponseEntity<ApiErrorResponse> notFound(HttpServletRequest r){return error(HttpStatus.NOT_FOUND,"HERD_ANIMAL_NOT_FOUND","O animal não foi encontrado",r);}
 @ExceptionHandler(HerdPaddockNotFoundException.class) ResponseEntity<ApiErrorResponse> paddockNotFound(HttpServletRequest r){return error(HttpStatus.NOT_FOUND,"HERD_PADDOCK_NOT_FOUND","O piquete não foi encontrado",r);}
 @ExceptionHandler(HerdAnimalVersionConflictException.class) ResponseEntity<ApiErrorResponse> version(HttpServletRequest r){return error(HttpStatus.CONFLICT,"HERD_VERSION_CONFLICT","A versão do animal está desatualizada",r);}
 @ExceptionHandler(HerdAnimalIdentificationConflictException.class) ResponseEntity<ApiErrorResponse> identification(HttpServletRequest r){return error(HttpStatus.CONFLICT,"HERD_IDENTIFICATION_CONFLICT","A identificação do animal já está em uso",r);}
 @ExceptionHandler(HerdAnimalIdempotencyConflictException.class) ResponseEntity<ApiErrorResponse> idempotency(HttpServletRequest r){return error(HttpStatus.CONFLICT,"HERD_IDEMPOTENCY_CONFLICT","O comando de criação conflita com um animal existente",r);}
 @ExceptionHandler(HerdLifecycleConflictException.class) ResponseEntity<ApiErrorResponse> lifecycleConflict(HttpServletRequest r){return error(HttpStatus.CONFLICT,"HERD_LIFECYCLE_CONFLICT","A transição de ciclo de vida não é permitida",r);}
 @ExceptionHandler(HerdPaddockConflictException.class) ResponseEntity<ApiErrorResponse> paddockConflict(HttpServletRequest r){return error(HttpStatus.CONFLICT,"HERD_PADDOCK_CONFLICT","Os dados do piquete conflitam com um registro existente",r);}
 @ExceptionHandler(HerdPaddockOccupiedException.class) ResponseEntity<ApiErrorResponse> paddockOccupied(HttpServletRequest r){return error(HttpStatus.CONFLICT,"HERD_PADDOCK_OCCUPIED","O piquete possui animais alocados",r);}
 @ExceptionHandler(HerdMovementConflictException.class) ResponseEntity<ApiErrorResponse> movementConflict(HttpServletRequest r){return error(HttpStatus.CONFLICT,"HERD_MOVEMENT_CONFLICT","A movimentação não é permitida no estado atual",r);}
 @ExceptionHandler(HerdTransferConflictException.class) ResponseEntity<ApiErrorResponse> transferConflict(HttpServletRequest r){return error(HttpStatus.CONFLICT,"HERD_TRANSFER_CONFLICT","A transferência não é permitida no estado atual",r);}
 @ExceptionHandler(HerdTransferIdentificationConflictException.class) ResponseEntity<ApiErrorResponse> transferIdentification(HttpServletRequest r){return error(HttpStatus.CONFLICT,"HERD_TRANSFER_IDENTIFICATION_CONFLICT","A identificação do animal já está em uso na fazenda de destino",r);}
 @ExceptionHandler(HerdOperationIdempotencyConflictException.class) ResponseEntity<ApiErrorResponse> operationConflict(HttpServletRequest r){return error(HttpStatus.CONFLICT,"HERD_OPERATION_IDEMPOTENCY_CONFLICT","A operação informada conflita com o histórico existente",r);}
 @ExceptionHandler(HerdPlannerExceptions.NotFound.class) ResponseEntity<ApiErrorResponse> plannerNotFound(HttpServletRequest r){return error(HttpStatus.NOT_FOUND,"HERD_PLANNER_ITEM_NOT_FOUND","O item do planejador não foi encontrado",r);}
 @ExceptionHandler({HerdPlannerExceptions.Conflict.class,HerdPlannerExceptions.InvalidState.class}) ResponseEntity<ApiErrorResponse> plannerConflict(HttpServletRequest r){return error(HttpStatus.CONFLICT,"HERD_PLANNER_ITEM_CONFLICT","A operação do planejador conflita com o estado atual",r);}
 @ExceptionHandler(HerdPlannerExceptions.Forbidden.class) ResponseEntity<ApiErrorResponse> plannerForbidden(HttpServletRequest r){return error(HttpStatus.FORBIDDEN,"HERD_PLANNER_FORBIDDEN","A operação do planejador não é permitida",r);}
 @ExceptionHandler(HerdReportForbiddenException.class) ResponseEntity<ApiErrorResponse> reportForbidden(HttpServletRequest r){return error(HttpStatus.FORBIDDEN,"HERD_REPORT_FORBIDDEN","A consulta de relatórios não é permitida",r);}
 @ExceptionHandler(HerdDashboardForbiddenException.class) ResponseEntity<ApiErrorResponse> dashboardForbidden(HttpServletRequest r){return error(HttpStatus.FORBIDDEN,"HERD_DASHBOARD_FORBIDDEN","A consulta do dashboard não é permitida",r);}
 @ExceptionHandler({DataAccessException.class,TransactionException.class,TenantTransactionInfrastructureException.class}) ResponseEntity<ApiErrorResponse> unavailable(HttpServletRequest r){return error(HttpStatus.SERVICE_UNAVAILABLE,"HERD_PERSISTENCE_UNAVAILABLE","A consulta de animais está temporariamente indisponível",r);}
 private ResponseEntity<ApiErrorResponse> error(HttpStatus s,String c,String m,HttpServletRequest r){Object id=r.getAttribute(RequestContextFilter.REQUEST_ID_ATTRIBUTE);return ResponseEntity.status(s).cacheControl(CacheControl.noStore()).body(new ApiErrorResponse(c,m,s.value(),id==null?null:id.toString(),List.of(),Instant.now()));}}
