package com.gerenciadorrural.modules.herd.api;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.gerenciadorrural.modules.herd.application.*;
import com.gerenciadorrural.modules.herd.domain.*;
import com.gerenciadorrural.modules.organizations.api.ResolvedTenantContext;
import com.gerenciadorrural.shared.tenancy.TenantContext;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.http.*;
import org.springframework.web.bind.annotation.*;
import org.springframework.beans.factory.annotation.Autowired;
import java.time.LocalDate;
import java.util.*;

@RestController @RequestMapping("/api/v1/herd/animals") public class HerdAnimalController {
 private static final Set<String> ALLOWED=Set.of("search","sex","status","page","size"); private static final long MAX_OFFSET=Integer.MAX_VALUE;
 private final ListCurrentFarmAnimals list; private final CreateCurrentFarmAnimal create; private final GetCurrentFarmAnimal getById; private final CorrectCurrentFarmAnimal correct; private final LifecycleCurrentFarmAnimal lifecycle; private final GetCurrentFarmAnimalHistory history;
 @Autowired public HerdAnimalController(ListCurrentFarmAnimals list,CreateCurrentFarmAnimal create,GetCurrentFarmAnimal getById,CorrectCurrentFarmAnimal correct,LifecycleCurrentFarmAnimal lifecycle,GetCurrentFarmAnimalHistory history){this.list=list;this.create=create;this.getById=getById;this.correct=correct;this.lifecycle=lifecycle;this.history=history;}
 /** Mantém os testes de contrato legados focados nos endpoints já existentes. */
 public HerdAnimalController(ListCurrentFarmAnimals list,CreateCurrentFarmAnimal create){this(list,create,null,null,null,null);}
 @GetMapping public ResponseEntity<Response> get(@ResolvedTenantContext TenantContext context,@RequestParam(required=false) String search,@RequestParam(required=false) String sex,@RequestParam(required=false) String status,@RequestParam(required=false) String page,@RequestParam(required=false) String size,HttpServletRequest request){if(!ALLOWED.containsAll(request.getParameterMap().keySet())||request.getParameterMap().values().stream().anyMatch(v->v.length!=1))throw new HerdAnimalQueryException();var result=list.execute(context,query(search,sex,status,page,size));return ResponseEntity.ok().cacheControl(CacheControl.noStore()).body(Response.from(result));}
 @PostMapping public ResponseEntity<Item> create(@ResolvedTenantContext TenantContext context,@RequestBody CreateRequest request){var result=create.execute(context,new CreateCurrentFarmAnimalCommand(request.id(),request.identification(),request.name(),request.sex(),request.birthDate()));return ResponseEntity.status(result.outcome()==CreateCurrentFarmAnimalResult.Outcome.CREATED?HttpStatus.CREATED:HttpStatus.OK).cacheControl(CacheControl.noStore()).body(Item.from(result.animal()));}
 @GetMapping("/{id}") public ResponseEntity<Profile> getById(@ResolvedTenantContext TenantContext context,@PathVariable UUID id){return ResponseEntity.ok().cacheControl(CacheControl.noStore()).body(Profile.from(getById.execute(context,id)));}
 @PatchMapping("/{id}") public ResponseEntity<Item> correct(@ResolvedTenantContext TenantContext context,@PathVariable UUID id,@RequestBody CorrectionRequest request){return ResponseEntity.ok().cacheControl(CacheControl.noStore()).body(Item.from(correct.execute(context,id,new CorrectCurrentFarmAnimalCommand(request.expectedVersion(),request.identification(),request.name(),request.sex(),request.birthDate()))));}
 @PostMapping("/{id}/sale") public ResponseEntity<Item> sale(@ResolvedTenantContext TenantContext c,@PathVariable UUID id,@RequestBody LifecycleRequest r){return ResponseEntity.ok().cacheControl(CacheControl.noStore()).body(Item.from(lifecycle.sale(c,id,new LifecycleCurrentFarmAnimalCommand(r.operationId(),r.expectedVersion(),r.occurredOn(),r.notes()))));}
 @PostMapping("/{id}/death") public ResponseEntity<Item> death(@ResolvedTenantContext TenantContext c,@PathVariable UUID id,@RequestBody LifecycleRequest r){return ResponseEntity.ok().cacheControl(CacheControl.noStore()).body(Item.from(lifecycle.death(c,id,new LifecycleCurrentFarmAnimalCommand(r.operationId(),r.expectedVersion(),r.occurredOn(),r.notes()))));}
 @GetMapping("/{id}/history") public ResponseEntity<History> history(@ResolvedTenantContext TenantContext c,@PathVariable UUID id,@RequestParam(required=false) String page,@RequestParam(required=false) String size,@RequestParam(required=false) String type,HttpServletRequest r){if(!Set.of("page","size","type").containsAll(r.getParameterMap().keySet())||r.getParameterMap().values().stream().anyMatch(v->v.length!=1))throw new HerdAnimalQueryException();try{int p=page==null?0:Integer.parseInt(page),s=size==null?20:Integer.parseInt(size);if(p<0||s<1||s>100)throw new IllegalArgumentException();var x=history.execute(c,id,type==null?null:AnimalEventType.valueOf(type),p,s);return ResponseEntity.ok().cacheControl(CacheControl.noStore()).body(History.from(x));}catch(IllegalArgumentException e){throw new HerdAnimalQueryException();}}
 private HerdAnimalQuery query(String search,String sex,String status,String page,String size){try{String normalized=search==null?null:search.trim();if(normalized!=null&&normalized.isEmpty())normalized=null;if(normalized!=null&&normalized.length()>100)throw new HerdAnimalQueryException();int p=page==null?0:Integer.parseInt(page),s=size==null?50:Integer.parseInt(size);if(p<0||s<1||s>100)throw new HerdAnimalQueryException();long offset=(long)p*s;if(offset>MAX_OFFSET)throw new HerdAnimalQueryException();return new HerdAnimalQuery(normalized,sex==null?null:HerdAnimalSex.valueOf(sex),status==null?null:HerdAnimalStatus.valueOf(status),p,s);}catch(IllegalArgumentException e){throw new HerdAnimalQueryException();}}
 public record Response(List<Item> items,int page,int size,long totalElements,int totalPages){static Response from(HerdAnimalPage p){return new Response(p.items().stream().map(Item::from).toList(),p.page(),p.size(),p.totalElements(),p.totalPages());}}
 public record Item(String id,String identification,String name,String sex,LocalDate birthDate,String status,long version,@JsonInclude(JsonInclude.Include.NON_NULL) PaddockItem paddock){static Item from(HerdAnimalSummary a){return new Item(a.id().toString(),a.identification(),a.name(),a.sex().name(),a.birthDate(),a.status().name(),a.version(),PaddockItem.from(a.paddock()));}}
 public record Profile(String id,String identification,String name,String sex,LocalDate birthDate,String status,long version,PaddockItem paddock){static Profile from(HerdAnimalSummary a){return new Profile(a.id().toString(),a.identification(),a.name(),a.sex().name(),a.birthDate(),a.status().name(),a.version(),PaddockItem.from(a.paddock()));}}
 @JsonIgnoreProperties(ignoreUnknown=false) @JsonDeserialize(using=HerdAnimalCreateRequestDeserializer.class) public record CreateRequest(UUID id,String identification,String name,HerdAnimalSex sex,LocalDate birthDate){}
 @JsonIgnoreProperties(ignoreUnknown=false) @JsonDeserialize(using=HerdAnimalCorrectionRequestDeserializer.class) public record CorrectionRequest(Long expectedVersion,HerdAnimalPatch<String> identification,HerdAnimalPatch<String> name,HerdAnimalPatch<HerdAnimalSex> sex,HerdAnimalPatch<LocalDate> birthDate){}
 @JsonIgnoreProperties(ignoreUnknown=false) @JsonDeserialize(using=HerdAnimalLifecycleRequestDeserializer.class) public record LifecycleRequest(UUID operationId,Long expectedVersion,LocalDate occurredOn,String notes){}
 public record EventItem(String id,String type,LocalDate occurredOn,java.time.Instant recordedAt,long resultingVersion,String actorUserId,AnimalEventDetails details){static EventItem from(AnimalEvent e){return new EventItem(e.id().toString(),e.type().name(),e.occurredOn(),e.recordedAt(),e.resultingVersion(),e.actorUserId()==null?null:e.actorUserId().toString(),e.details());}}
 public record History(List<EventItem> items,int page,int size,long totalElements,int totalPages){static History from(GetCurrentFarmAnimalHistory.Result r){return new History(r.items().stream().map(EventItem::from).toList(),r.page(),r.size(),r.totalElements(),r.totalPages());}}
}
