package com.gerenciadorrural.modules.herd.api;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.gerenciadorrural.modules.herd.application.*; import com.gerenciadorrural.modules.herd.domain.*; import com.gerenciadorrural.modules.organizations.api.ResolvedTenantContext; import com.gerenciadorrural.shared.tenancy.TenantContext; import jakarta.servlet.http.HttpServletRequest; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.math.*; import java.time.*; import java.util.*;
@RestController @RequestMapping("/api/v1/herd") public class HerdIntelligenceController {
 private final ManageHerdIntelligence m; private final ReadHerdPendingWork pending;
 public HerdIntelligenceController(ManageHerdIntelligence m,ReadHerdPendingWork pending){this.m=m;this.pending=pending;}
 @GetMapping("/pending-work") ResponseEntity<?> pending(@ResolvedTenantContext TenantContext c,@RequestParam(required=false) PendingWorkType type,@RequestParam(required=false) UUID animalId,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="20") int size,HttpServletRequest request){if(!Set.of("type","animalId","page","size").containsAll(request.getParameterMap().keySet())||request.getParameterMap().values().stream().anyMatch(v->v.length!=1))throw new HerdAnimalQueryException();return ResponseEntity.ok().cacheControl(CacheControl.noStore()).body(pending.page(c,type,animalId,page,size));}
 @GetMapping("/animals/{id}/weights") ResponseEntity<?> weights(@ResolvedTenantContext TenantContext c,@PathVariable UUID id,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){return ResponseEntity.ok().cacheControl(CacheControl.noStore()).body(m.weightHistory(c,id,page,size));}
 @GetMapping("/animals/{id}/health-treatments") ResponseEntity<?> treatments(@ResolvedTenantContext TenantContext c,@PathVariable UUID id,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){return ResponseEntity.ok().cacheControl(CacheControl.noStore()).body(m.treatmentHistory(c,id,page,size));}
 @PostMapping("/animals/{id}/weights") ResponseEntity<ManageHerdIntelligence.Result> weight(@ResolvedTenantContext TenantContext c,@PathVariable UUID id,@RequestBody Weight r){return ResponseEntity.ok().cacheControl(CacheControl.noStore()).body(m.weights(c,r.operationId(),List.of(new ManageHerdIntelligence.WeightCommand(id,r.expectedVersion(),r.weightKg(),r.measuredOn(),r.notes()))));}
 @PostMapping("/weights/batch") ResponseEntity<ManageHerdIntelligence.Result> batchWeight(@ResolvedTenantContext TenantContext c,@RequestBody WeightBatch r){return ResponseEntity.ok().cacheControl(CacheControl.noStore()).body(m.weights(c,r.operationId(),r.animals()));}
 @PostMapping("/animals/{id}/health-treatments") ResponseEntity<ManageHerdIntelligence.Result> health(@ResolvedTenantContext TenantContext c,@PathVariable UUID id,@RequestBody Health r){return ResponseEntity.ok().cacheControl(CacheControl.noStore()).body(m.health(c,r.operationId(),r.treatmentType(),r.occurredOn(),r.product(),r.protocol(),r.nextDueOn(),r.notes(),List.of(new ManageHerdIntelligence.BasicAnimalCommand(id,r.expectedVersion()))));}
 @PostMapping("/health-treatments/batch") ResponseEntity<ManageHerdIntelligence.Result> batchHealth(@ResolvedTenantContext TenantContext c,@RequestBody HealthBatch r){return ResponseEntity.ok().cacheControl(CacheControl.noStore()).body(m.health(c,r.operationId(),r.treatmentType(),r.occurredOn(),r.product(),r.protocol(),r.nextDueOn(),r.notes(),r.animals()));}
 @JsonIgnoreProperties(ignoreUnknown=false) public record Weight(UUID operationId,long expectedVersion,BigDecimal weightKg,LocalDate measuredOn,String notes){} @JsonIgnoreProperties(ignoreUnknown=false) public record WeightBatch(UUID operationId,List<ManageHerdIntelligence.WeightCommand> animals){} @JsonIgnoreProperties(ignoreUnknown=false) public record Health(UUID operationId,long expectedVersion,HealthTreatmentType treatmentType,LocalDate occurredOn,String product,String protocol,LocalDate nextDueOn,String notes){} @JsonIgnoreProperties(ignoreUnknown=false) public record HealthBatch(UUID operationId,HealthTreatmentType treatmentType,LocalDate occurredOn,String product,String protocol,LocalDate nextDueOn,String notes,List<ManageHerdIntelligence.BasicAnimalCommand> animals){}
}
