package com.gerenciadorrural.infrastructure.database;

import com.gerenciadorrural.modules.herd.domain.*; import com.gerenciadorrural.modules.herd.infrastructure.JdbcHerdAnimalProfileRepository; import com.gerenciadorrural.shared.infrastructure.database.*; import com.gerenciadorrural.shared.tenancy.*; import com.zaxxer.hikari.*; import org.junit.jupiter.api.*; import org.springframework.jdbc.core.*; import org.springframework.jdbc.core.namedparam.*; import org.springframework.jdbc.datasource.DataSourceTransactionManager; import org.springframework.transaction.support.TransactionTemplate; import java.sql.*; import java.time.*; import java.util.*; import static org.assertj.core.api.Assertions.*;

class HerdAnimalProfileRepositoryIntegrationTest extends PostgresMigrationTestSupport {
 HikariDataSource ds; SpringTenantTransactionExecutor tx; JdbcHerdAnimalProfileRepository repo; UUID tenantA,tenantB,farmA,farmA2,farmB,id;
 @BeforeEach void setup()throws Exception{try(Connection c=adminConnection();Statement s=c.createStatement()){s.execute("do $$ begin if not exists(select 1 from pg_roles where rolname='herd_profile_runtime') then create role herd_profile_runtime login noinherit password 'profile-test';end if;grant app_api to herd_profile_runtime;end $$");}var cfg=new HikariConfig();cfg.setJdbcUrl(POSTGRES.getJdbcUrl());cfg.setUsername("herd_profile_runtime");cfg.setPassword("profile-test");ds=new HikariDataSource(cfg);var jdbc=new JdbcTemplate(ds);tx=new SpringTenantTransactionExecutor(new TransactionTemplate(new DataSourceTransactionManager(ds)),new NamedParameterJdbcTemplate(ds),new TransactionalDatabaseRole(jdbc,new DatabaseAccessProperties("app","app_api")));repo=new JdbcHerdAnimalProfileRepository(new NamedParameterJdbcTemplate(ds));tenantA=org();tenantB=org();farmA=farm(tenantA);farmA2=farm(tenantA);farmB=farm(tenantB);id=UUID.randomUUID();animal(id,tenantA,farmA,"A-001","Brisa",0);}
 @AfterEach void close(){ds.close();}
 @Test void scopesFindAndUpdatesWithVersionAndPreservesServerFields()throws Exception{Instant createdAt;try(Connection c=adminConnection();PreparedStatement p=c.prepareStatement("select created_at from app.animals where id=?")){p.setObject(1,id);var r=p.executeQuery();assertThat(r.next()).isTrue();createdAt=r.getTimestamp(1).toInstant();}assertThat(run(tenantA,farmA,()->repo.findById(new TenantId(tenantA),farmA,id))).isPresent();assertThat(run(tenantA,farmA2,()->repo.findById(new TenantId(tenantA),farmA2,id))).isEmpty();assertThat(run(tenantB,farmB,()->repo.findById(new TenantId(tenantB),farmB,id))).isEmpty();assertThat(run(tenantA,farmA,()->repo.update(new TenantId(tenantA),farmA,id,0,"A-002",null,HerdAnimalSex.MALE,null))).hasValueSatisfying(a->{assertThat(a.version()).isEqualTo(1);assertThat(a.name()).isNull();});assertThat(run(tenantA,farmA,()->repo.update(new TenantId(tenantA),farmA,id,0,"x",null,HerdAnimalSex.MALE,null))).isEmpty();assertThat(run(tenantA,farmA,()->repo.update(new TenantId(tenantA),farmA,id,1,"A-003","Nova",HerdAnimalSex.FEMALE,LocalDate.of(2020,1,1)))).hasValueSatisfying(a->assertThat(a.version()).isEqualTo(2));try(Connection c=adminConnection();PreparedStatement p=c.prepareStatement("select tenant_id,farm_id,status,created_at,version from app.animals where id=?")){p.setObject(1,id);var r=p.executeQuery();r.next();assertThat(r.getObject(1,UUID.class)).isEqualTo(tenantA);assertThat(r.getObject(2,UUID.class)).isEqualTo(farmA);assertThat(r.getString(3)).isEqualTo("ACTIVE");assertThat(r.getTimestamp(4).toInstant()).isEqualTo(createdAt);assertThat(r.getLong(5)).isEqualTo(2);}}
 @Test void mapsStructuredIdentificationConflict()throws Exception{UUID other=UUID.randomUUID();animal(other,tenantA,farmA,"B-001","Outra",0);assertThatThrownBy(()->run(tenantA,farmA,()->repo.update(new TenantId(tenantA),farmA,other,0," \tA-001\r\n","Outra",HerdAnimalSex.FEMALE,null))).isInstanceOf(HerdAnimalWriteConflictException.class).satisfies(e->assertThat(((HerdAnimalWriteConflictException)e).type()).isEqualTo(HerdAnimalWriteConflictException.Type.IDENTIFICATION_CONFLICT));}
 <T>T run(UUID t,UUID f,TenantTransactionalOperation<T> op){return tx.execute(new TenantContext(new TenantId(t),UUID.randomUUID(),f,UUID.randomUUID(),"OWNER","ALL_FARMS"),op);} UUID org()throws Exception{UUID x=UUID.randomUUID();executeAsAdmin("insert into app.organizations(id,name,status) values(?,?,'ACTIVE')",x,"Org");return x;}UUID farm(UUID t)throws Exception{UUID x=UUID.randomUUID();executeAsAdmin("insert into app.farms(id,tenant_id,name,status) values(?,?,?,'ACTIVE')",x,t,"Farm");return x;}void animal(UUID x,UUID t,UUID f,String identification,String name,long version)throws Exception{executeAsAdmin("insert into app.animals(id,tenant_id,farm_id,identification,name,sex,version) values(?,?,?,?,?,'FEMALE',?)",x,t,f,identification,name,version);}
}
