package com.gerenciadorrural.modules.herd.domain;
public enum AnimalEventType { CREATED, CORRECTED, SOLD, DECEASED, MOVED, TRANSFERRED_OUT, TRANSFERRED_IN, WEIGHED, HEALTH_TREATMENT, BREEDING_RECORDED, PREGNANCY_CONFIRMED, PREGNANCY_ENDED, CALVED, BORN }
