package com.gerenciadorrural.modules.herd.domain;

public enum PendingWorkType { VACCINATION_DUE, DEWORMING_DUE, WEIGHING_DUE, CALVING_UPCOMING, CALVING_OVERDUE, BRUCELLOSIS_DUE, BRUCELLOSIS_WINDOW_MISSED }
