package com.gerenciadorrural.modules.herd.application;
import com.fasterxml.jackson.databind.ObjectMapper; import com.gerenciadorrural.modules.herd.domain.*; import com.gerenciadorrural.shared.tenancy.*; import org.springframework.stereotype.Service; import java.time.*; import java.util.*;
@Service public class MoveCurrentFarmAnimals {
 private static final Set<String> ROLES=Set.of("OWNER","ADMIN","MANAGER","OPERATOR"); private final TenantTransactionExecutor tx; private final HerdAnimalProfileRepository animals; private final PaddockRepository paddocks; private final AnimalEventRepository events; private final MovementOperationRepository operations; private final Clock clock; private final ObjectMapper mapper;
 public MoveCurrentFarmAnimals(TenantTransactionExecutor tx,HerdAnimalProfileRepository animals,PaddockRepository paddocks,AnimalEventRepository events,MovementOperationRepository operations,Clock clock,ObjectMapper mapper){this.tx=tx;this.animals=animals;this.paddocks=paddocks;this.events=events;this.operations=operations;this.clock=clock;this.mapper=mapper;}
 public HerdAnimalSummary one(TenantContext c,UUID animal,UUID op,Long expected,UUID destination,LocalDate occurred,String notes){authorize(c);Valid v=valid(op,destination,occurred,notes);if(animal==null||expected==null||expected<0)throw new HerdAnimalCommandInvalidException();List<Animal> xs=List.of(new Animal(animal,expected));String canonical=canonical(v,xs);return tx.execute(c,()->{List<HerdAnimalSummary> r=execute(c,v,xs,canonical);return r.getFirst();});}
 public BatchResult batch(TenantContext c,UUID op,UUID destination,LocalDate occurred,String notes,List<Animal> input){authorize(c);Valid v=valid(op,destination,occurred,notes);if(input==null||input.isEmpty()||input.size()>100)throw new HerdAnimalCommandInvalidException();Set<UUID> ids=new HashSet<>();for(Animal a:input)if(a==null||a.id()==null||a.expectedVersion()<0||!ids.add(a.id()))throw new HerdAnimalCommandInvalidException();List<Animal> xs=input.stream().sorted(Comparator.comparing(x->x.id().toString())).toList();String canonical=canonical(v,xs);return tx.execute(c,()->{List<HerdAnimalSummary> moved=execute(c,v,xs,canonical);PaddockSummary d=paddocks.find(c.tenantId(),c.farmId(),v.destination()).orElseThrow(HerdPaddockNotFoundException::new);return new BatchResult(v.operation(),d,moved);});}
 private List<HerdAnimalSummary> execute(TenantContext c,Valid v,List<Animal> xs,String canonical){events.lockOperation(c.tenantId(),c.farmId(),v.operation());Optional<String> old=operations.payload(c.tenantId(),c.farmId(),v.operation());if(old.isPresent()){if(!old.get().equals(canonical))throw new HerdOperationIdempotencyConflictException();return replay(c,xs,v.operation());}PaddockSummary destination=paddocks.lock(c.tenantId(),c.farmId(),v.destination()).orElseThrow(HerdPaddockNotFoundException::new);List<HerdAnimalSummary> current=new ArrayList<>();for(Animal a:xs){HerdAnimalSummary h=animals.findByIdForCorrection(c.tenantId(),c.farmId(),a.id()).orElseThrow(HerdAnimalNotFoundException::new);if(h.version()!=a.expectedVersion())throw new HerdAnimalVersionConflictException();if(h.status()!=HerdAnimalStatus.ACTIVE||Objects.equals(h.paddock()==null?null:h.paddock().id(),v.destination()))throw new HerdMovementConflictException();if(h.birthDate()!=null&&v.occurred().isBefore(h.birthDate()))throw new HerdAnimalCommandInvalidException();current.add(h);}if(destination.status()!=PaddockStatus.ACTIVE)throw new HerdMovementConflictException();operations.save(c.tenantId(),c.farmId(),v.operation(),canonical);List<HerdAnimalSummary> out=new ArrayList<>();for(int i=0;i<xs.size();i++){HerdAnimalSummary h=current.get(i);HerdAnimalSummary updated=animals.updatePaddock(c.tenantId(),c.farmId(),h.id(),h.version(),v.destination()).orElseThrow(HerdAnimalVersionConflictException::new);MovedEventDetails details=new MovedEventDetails(h.paddock()==null?null:h.paddock().id(),h.paddock()==null?null:h.paddock().name(),destination.id(),destination.name(),v.notes());events.recordMovement(c.tenantId(),c.farmId(),h.id(),v.operation(),c.userId(),v.occurred(),updated.version(),details);out.add(new HerdAnimalSummary(updated.id(),updated.identification(),updated.name(),updated.sex(),updated.birthDate(),updated.status(),updated.version(),destination));}return out;}
 private List<HerdAnimalSummary> replay(TenantContext c,List<Animal> xs,UUID op){List<HerdAnimalSummary> out=new ArrayList<>();for(Animal a:xs){AnimalEvent e=events.findByOperation(c.tenantId(),c.farmId(),op).filter(x->x.animalId().equals(a.id())&&x.type()==AnimalEventType.MOVED).orElse(null); // repository implementation returns first: query current state is authoritative for compact replay
 HerdAnimalSummary h=animals.findById(c.tenantId(),c.farmId(),a.id()).orElseThrow(HerdOperationIdempotencyConflictException::new);out.add(h);}return out;}
 private Valid valid(UUID op,UUID dest,LocalDate date,String notes){if(op==null||dest==null||date==null||date.isAfter(LocalDate.now(clock)))throw new HerdAnimalCommandInvalidException();String n=notes==null?null:PosixEdgeWhitespace.trim(notes);if(n!=null&&(n.isEmpty()||n.indexOf('\0')>=0||n.codePointCount(0,n.length())>1000))throw new HerdAnimalCommandInvalidException();return new Valid(op,dest,date,n);} private void authorize(TenantContext c){if(!ROLES.contains(c.role()))throw new HerdMovementForbiddenException();} private String canonical(Valid v,List<Animal> xs){try{Map<String,Object> payload=new LinkedHashMap<>();payload.put("destinationPaddockId",v.destination().toString());payload.put("occurredOn",v.occurred().toString());payload.put("notes",v.notes()==null?"":v.notes());payload.put("animals",xs.stream().map(x->{Map<String,Object> animal=new LinkedHashMap<>();animal.put("animalId",x.id().toString());animal.put("expectedVersion",x.expectedVersion());return animal;}).toList());return mapper.writeValueAsString(payload);}catch(Exception e){throw new IllegalStateException(e);}} private record Valid(UUID operation,UUID destination,LocalDate occurred,String notes){} public record Animal(UUID id,long expectedVersion){} public record BatchResult(UUID operationId,PaddockSummary destinationPaddock,List<HerdAnimalSummary> animals){public int movedCount(){return animals.size();}}
}
