package com.gerenciadorrural.modules.herd.application;
import com.gerenciadorrural.modules.herd.domain.*; import com.gerenciadorrural.shared.tenancy.*; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.stereotype.Service; import java.util.*;
@Service public class PaddockCurrentFarm {
 private static final Set<String> WRITE=Set.of("OWNER","ADMIN","MANAGER"); private final TenantTransactionExecutor tx; private final PaddockRepository paddocks;
 public PaddockCurrentFarm(TenantTransactionExecutor tx,PaddockRepository paddocks){this.tx=tx;this.paddocks=paddocks;}
 public Result create(TenantContext c,UUID id,String name,String code){write(c);PaddockSummary p=new PaddockSummary(required(id),text(name,120,true),code==null?null:text(code,60,true),PaddockStatus.ACTIVE,0);return tx.execute(c,()->{Optional<PaddockSummary> old=paddocks.find(c.tenantId(),c.farmId(),id);if(old.isPresent()){if(same(old.get(),p))return new Result(old.get(),false);throw new HerdPaddockConflictException();}try{return new Result(paddocks.create(c.tenantId(),c.farmId(),p).orElseThrow(HerdPaddockConflictException::new),true);}catch(DataIntegrityViolationException e){throw new HerdPaddockConflictException();}});}
 public PaddockSummary get(TenantContext c,UUID id){return tx.execute(c,()->paddocks.find(c.tenantId(),c.farmId(),id).orElseThrow(HerdPaddockNotFoundException::new));}
 public PaddockSummary patch(TenantContext c,UUID id,Long version,HerdAnimalPatch<String> name,HerdAnimalPatch<String> code,HerdAnimalPatch<PaddockStatus> status){write(c);if(version==null||version<0||name==null||code==null||status==null||(!name.present()&&!code.present()&&!status.present())||(status.present()&&status.value()==null))throw new HerdAnimalCommandInvalidException();return tx.execute(c,()->{PaddockSummary current=paddocks.lock(c.tenantId(),c.farmId(),id).orElseThrow(HerdPaddockNotFoundException::new);if(current.version()!=version)throw new HerdAnimalVersionConflictException();String n=name.present()?text(name.value(),120,true):current.name();String co=code.present()?(code.value()==null?null:text(code.value(),60,true)):current.code();PaddockStatus st=status.present()?status.value():current.status();if(st==PaddockStatus.INACTIVE&&current.status()!=PaddockStatus.INACTIVE&&paddocks.occupancy(c.tenantId(),c.farmId(),id)>0)throw new HerdPaddockOccupiedException();PaddockSummary target=new PaddockSummary(id,n,co,st,current.version());if(same(current,target))return current;try{return paddocks.update(c.tenantId(),c.farmId(),target,version).orElseThrow(HerdAnimalVersionConflictException::new);}catch(DataIntegrityViolationException e){throw new HerdPaddockConflictException();}});}
 public PaddockPage list(TenantContext c,PaddockStatus s,String search,int page,int size){validPage(page,size);String q=search==null?null:PosixEdgeWhitespace.trim(search);if(q!=null&&(q.isEmpty()||q.indexOf('\0')>=0||q.codePointCount(0,q.length())>120))throw new HerdAnimalCommandInvalidException();return tx.execute(c,()->paddocks.list(c.tenantId(),c.farmId(),s,q,page,size));}
 public Occupancy occupancy(TenantContext c,UUID id){return tx.execute(c,()->{PaddockSummary p=paddocks.find(c.tenantId(),c.farmId(),id).orElseThrow(HerdPaddockNotFoundException::new);return new Occupancy(p,paddocks.occupancy(c.tenantId(),c.farmId(),id),paddocks.occupancyByStatus(c.tenantId(),c.farmId(),id));});}
 public HerdAnimalPage animals(TenantContext c,UUID id,int page,int size){validPage(page,size);return tx.execute(c,()->{paddocks.find(c.tenantId(),c.farmId(),id).orElseThrow(HerdPaddockNotFoundException::new);return paddocks.animals(c.tenantId(),c.farmId(),id,page,size);});}
 private static UUID required(UUID x){if(x==null)throw new HerdAnimalCommandInvalidException();return x;} private static String text(String x,int max,boolean needed){if(x==null&&needed)throw new HerdAnimalCommandInvalidException();if(x==null)return null;String n=PosixEdgeWhitespace.trim(x);if(n.isEmpty()||n.indexOf('\0')>=0||n.codePointCount(0,n.length())>max)throw new HerdAnimalCommandInvalidException();return n;} private static boolean same(PaddockSummary a,PaddockSummary b){return a.name().equals(b.name())&&Objects.equals(a.code(),b.code())&&a.status()==b.status();} private static void write(TenantContext c){if(!WRITE.contains(c.role()))throw new HerdPaddockForbiddenException();} private static void validPage(int p,int s){if(p<0||s<1||s>100)throw new HerdAnimalCommandInvalidException();}
 public record Result(PaddockSummary paddock,boolean created){} public record Occupancy(PaddockSummary paddock,long totalAnimals,Map<HerdAnimalStatus,Long> countsByStatus){}
}
