package com.gerenciadorrural.modules.herd.application;

import com.gerenciadorrural.modules.herd.domain.*;
import com.gerenciadorrural.shared.tenancy.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import java.time.*; import java.time.temporal.ChronoUnit; import java.util.*;

@Service public class ReadHerdPendingWork {
 private static final Set<String> ROLES=Set.of("OWNER","ADMIN","MANAGER","OPERATOR","VIEWER");
 private final TenantTransactionExecutor tx; private final HerdManagementRepository repo; private final Clock clock; private final int weighingDays, upcomingDays;
 public ReadHerdPendingWork(TenantTransactionExecutor tx,HerdManagementRepository repo,Clock clock,@Value("${herd.pending-work.weighing-due-days:90}") int weighingDays,@Value("${herd.pending-work.calving-upcoming-days:14}") int upcomingDays){this.tx=tx;this.repo=repo;this.clock=clock;if(weighingDays<0||upcomingDays<0)throw new IllegalArgumentException("As janelas de acompanhamento não podem ser negativas");this.weighingDays=weighingDays;this.upcomingDays=upcomingDays;}
 public Page page(TenantContext c,PendingWorkType type,UUID animalId,int page,int size){if(!ROLES.contains(c.role()))throw new HerdMovementForbiddenException();if(page<0||size<1||size>100||(long)page*size>Integer.MAX_VALUE)throw new HerdAnimalCommandInvalidException();LocalDate today=LocalDate.now(clock);if(type==PendingWorkType.BRUCELLOSIS_DUE||type==PendingWorkType.BRUCELLOSIS_WINDOW_MISSED)return tx.execute(c,()->brucellosis(c,type,animalId,page,size,today));if(type==null)return tx.execute(c,()->merged(c,animalId,page,size,today));return tx.execute(c,()->{var items=repo.pending(c.tenantId(),c.farmId(),today,weighingDays,upcomingDays,type,animalId,size,(long)page*size).stream().map(x->Item.from(x,today,weighingDays)).toList();return new Page(items,page,size,repo.pendingCount(c.tenantId(),c.farmId(),today,weighingDays,upcomingDays,type,animalId));});}
 private Page brucellosis(TenantContext c,PendingWorkType type,UUID animalId,int page,int size,LocalDate today){var items=brucellosisItems(c,animalId,today,type);items.sort(GLOBAL_ORDER);long total=items.size();long offset=(long)page*size;List<Item> slice=offset>=total?List.of():items.subList((int)offset,(int)Math.min(offset+size,total));return new Page(List.copyOf(slice),page,size,total);}
 private List<Item> brucellosisItems(TenantContext c,UUID animalId,LocalDate today,PendingWorkType only){var items=new ArrayList<Item>();for(var s:repo.brucellosisPendingCandidates(c.tenantId(),c.farmId(),today,animalId)){var state=BrucellosisPrimaryCompliance.evaluate(s.sex(),s.birthDate(),today,s.treatments());PendingWorkType type=state==BrucellosisPrimaryState.DUE_IN_WINDOW?PendingWorkType.BRUCELLOSIS_DUE:state==BrucellosisPrimaryState.WINDOW_MISSED?PendingWorkType.BRUCELLOSIS_WINDOW_MISSED:null;if(type==null||(only!=null&&type!=only))continue;LocalDate due=AgePolicy.reachesMonthsOn(s.birthDate(),9);LocalDate last=s.treatments().stream().map(HerdManagementRepository.Treatment::occurredOn).filter(Objects::nonNull).filter(d->!d.isAfter(today)).max(Comparator.naturalOrder()).orElse(null);items.add(new Item(type,s.animalId(),s.identification(),s.name(),s.farmId(),due,null,type==PendingWorkType.BRUCELLOSIS_WINDOW_MISSED?ChronoUnit.DAYS.between(due,today):null,type==PendingWorkType.BRUCELLOSIS_DUE?ChronoUnit.DAYS.between(today,due):null,null,HealthTreatmentType.VACCINATION,last,null));}return items;}
 private Page merged(TenantContext c,UUID animalId,int page,int size,LocalDate today){long legacyTotal=repo.pendingCount(c.tenantId(),c.farmId(),today,weighingDays,upcomingDays,null,animalId);var bruc=brucellosisItems(c,animalId,today,null);long globalTotal=legacyTotal+bruc.size();long offset=(long)page*size;if(offset>=globalTotal)return new Page(List.of(),page,size,globalTotal);long wanted=Math.min(offset+size,legacyTotal);if(wanted>Integer.MAX_VALUE)throw new HerdAnimalCommandInvalidException();int prefix=(int)wanted;var all=new ArrayList<>(repo.pending(c.tenantId(),c.farmId(),today,weighingDays,upcomingDays,null,animalId,prefix,0L).stream().map(x->Item.from(x,today,weighingDays)).toList());all.addAll(bruc);all.sort(GLOBAL_ORDER);List<Item> slice=all.subList((int)offset,(int)Math.min(offset+size,all.size()));return new Page(List.copyOf(slice),page,size,globalTotal);}
 private static final Comparator<Item> GLOBAL_ORDER=Comparator.comparing((Item i)->i.dueOn()!=null?i.dueOn():i.expectedOn()).thenComparing(i->i.type().name()).thenComparing(Item::animalId,ReadHerdPendingWork::compareUuid).thenComparing(Item::pregnancyId,Comparator.nullsFirst(ReadHerdPendingWork::compareUuid));
 private static int compareUuid(UUID a,UUID b){int c=Long.compareUnsigned(a.getMostSignificantBits(),b.getMostSignificantBits());return c!=0?c:Long.compareUnsigned(a.getLeastSignificantBits(),b.getLeastSignificantBits());}
 public record Page(List<Item> items,int page,int size,long totalElements){public int totalPages(){return totalElements==0?0:(int)((totalElements+size-1)/size);}}
 public record Item(PendingWorkType type,UUID animalId,String identification,String name,UUID farmId,LocalDate dueOn,LocalDate expectedOn,Long daysOverdue,Long daysUntil,UUID pregnancyId,HealthTreatmentType treatmentType,LocalDate lastPerformedOn,LocalDate lastWeightOn,DerivedReason reason){
 public Item(PendingWorkType type,UUID animalId,String identification,String name,UUID farmId,LocalDate dueOn,LocalDate expectedOn,Long daysOverdue,Long daysUntil,UUID pregnancyId,HealthTreatmentType treatmentType,LocalDate lastPerformedOn,LocalDate lastWeightOn){this(type,animalId,identification,name,farmId,dueOn,expectedOn,daysOverdue,daysUntil,pregnancyId,treatmentType,lastPerformedOn,lastWeightOn,null);}
 public ReproductiveIntelligencePolicy.CalvingAttention getCalvingAttention(){if(expectedOn==null)return null;LocalDate reference=daysOverdue!=null?expectedOn.plusDays(daysOverdue):expectedOn.minusDays(daysUntil==null?0:daysUntil);return ReproductiveIntelligencePolicy.calving(expectedOn,reference);}
 static Item from(HerdManagementRepository.Pending x,LocalDate now,int weighingDays){Long overdue=x.type()==PendingWorkType.CALVING_OVERDUE||x.type()==PendingWorkType.VACCINATION_DUE||x.type()==PendingWorkType.DEWORMING_DUE?ChronoUnit.DAYS.between(x.date(),now):null;Long until=x.type()==PendingWorkType.CALVING_UPCOMING?ChronoUnit.DAYS.between(now,x.date()):null;return new Item(x.type(),x.animalId(),x.identification(),x.name(),x.farmId(),x.type()==PendingWorkType.CALVING_UPCOMING||x.type()==PendingWorkType.CALVING_OVERDUE?null:x.date(),x.type()==PendingWorkType.CALVING_UPCOMING||x.type()==PendingWorkType.CALVING_OVERDUE?x.date():null,overdue,until,x.pregnancyId(),x.treatmentType(),x.lastPerformedOn(),x.lastWeightOn(),x.type()==PendingWorkType.WEIGHING_DUE?new DerivedReason("WEIGHING_RECORDED_DATE_WINDOW",now,weighingDays,x.lastWeightOn(),now.minusDays(weighingDays),x.lastWeightOn()==null?"Nenhuma pesagem registrada para o animal.":"A última pesagem alcançou a janela configurada de acompanhamento."):null);}}
 public record DerivedReason(String policy,LocalDate referenceDate,int windowDays,LocalDate sourceDate,LocalDate cutoffOn,String explanation){}
}
