package com.gerenciadorrural.modules.herd.application;
import com.fasterxml.jackson.databind.ObjectMapper; import com.gerenciadorrural.modules.herd.domain.*; import com.gerenciadorrural.shared.tenancy.*; import org.springframework.stereotype.Service; import java.time.*; import java.util.*;
@Service public class TransferCurrentFarmAnimals {
 private static final Set<String> WRITE=Set.of("OWNER","ADMIN","MANAGER"); private final TenantTransactionExecutor tx; private final HerdAnimalProfileRepository animals; private final HerdTransferRepository transfers; private final PaddockRepository paddocks; private final AnimalEventRepository events; private final Clock clock; private final ObjectMapper mapper;
 public TransferCurrentFarmAnimals(TenantTransactionExecutor tx,HerdAnimalProfileRepository animals,HerdTransferRepository transfers,PaddockRepository paddocks,AnimalEventRepository events,Clock clock,ObjectMapper mapper){this.tx=tx;this.animals=animals;this.transfers=transfers;this.paddocks=paddocks;this.events=events;this.clock=clock;this.mapper=mapper;}
 public Result one(TenantContext c,UUID animal,UUID op,Long expected,UUID destinationFarm,UUID destinationPaddock,LocalDate occurred,String notes){if(animal==null||expected==null||expected<0)throw new HerdAnimalCommandInvalidException();return run(c,op,destinationFarm,destinationPaddock,occurred,notes,List.of(new Animal(animal,expected)));}
 public Result batch(TenantContext c,UUID op,UUID destinationFarm,UUID destinationPaddock,LocalDate occurred,String notes,List<Animal> input){if(input==null||input.isEmpty()||input.size()>100)throw new HerdAnimalCommandInvalidException();Set<UUID> ids=new HashSet<>();for(Animal a:input)if(a==null||a.id()==null||a.expectedVersion()<0||!ids.add(a.id()))throw new HerdAnimalCommandInvalidException();return run(c,op,destinationFarm,destinationPaddock,occurred,notes,input);}
 private Result run(TenantContext c,UUID op,UUID dest,UUID paddock,LocalDate date,String notes,List<Animal> input){authorize(c);Valid v=valid(op,dest,date,notes);if(Objects.equals(c.farmId(),dest))throw new HerdTransferConflictException();List<Animal> xs=input.stream().sorted(Comparator.comparing(x->x.id().toString())).toList();String canonical=canonical(c,v,xs,paddock);return tx.execute(c,()->execute(c,v,xs,canonical,paddock));}
 private Result execute(TenantContext c,Valid v,List<Animal> xs,String canonical,UUID destinationPaddock){transfers.lockOperation(c.tenantId(),v.operation());Optional<String> prior=transfers.payload(c.tenantId(),v.operation());if(prior.isPresent()){if(!prior.get().equals(canonical))throw new HerdOperationIdempotencyConflictException();return replay(c,v.operation());}if(!transfers.canAccessFarm(c.tenantId(),c.membershipId(),c.farmScopeMode(),v.destination()))throw new HerdTransferForbiddenException();UUID first=c.farmId().toString().compareTo(v.destination().toString())<0?c.farmId():v.destination(), second=first.equals(c.farmId())?v.destination():c.farmId();HerdTransferRepository.Farm f1=transfers.lockFarm(c.tenantId(),first).orElseThrow(HerdTransferConflictException::new);HerdTransferRepository.Farm f2=transfers.lockFarm(c.tenantId(),second).orElseThrow(HerdTransferConflictException::new);HerdTransferRepository.Farm source=f1.id().equals(c.farmId())?f1:f2,destination=f1.id().equals(v.destination())?f1:f2;
 PaddockSummary dp=null;if(destinationPaddock!=null){dp=paddocks.lock(c.tenantId(),v.destination(),destinationPaddock).orElseThrow(HerdPaddockNotFoundException::new);if(dp.status()!=PaddockStatus.ACTIVE)throw new HerdTransferConflictException();}
 List<HerdAnimalSummary> current=new ArrayList<>();for(Animal x:xs){HerdAnimalSummary a=animals.findByIdForCorrection(c.tenantId(),c.farmId(),x.id()).orElseThrow(HerdAnimalNotFoundException::new);if(a.version()!=x.expectedVersion())throw new HerdAnimalVersionConflictException();if(a.status()!=HerdAnimalStatus.ACTIVE)throw new HerdTransferConflictException();if(a.birthDate()!=null&&v.occurred().isBefore(a.birthDate()))throw new HerdAnimalCommandInvalidException();if(transfers.identificationExists(c.tenantId(),v.destination(),a.identification(),a.id()))throw new HerdTransferIdentificationConflictException();current.add(a);}
 transfers.saveOperation(c.tenantId(),v.operation(),canonical);List<AnimalResult> out=new ArrayList<>();for(int i=0;i<xs.size();i++){HerdAnimalSummary a=current.get(i);HerdAnimalSummary updated=animals.transfer(c.tenantId(),c.farmId(),v.destination(),a.id(),a.version(),destinationPaddock).orElseThrow(HerdAnimalVersionConflictException::new);HerdTransferRepository.Row row=new HerdTransferRepository.Row(UUID.randomUUID(),a.id(),v.operation(),c.farmId(),v.destination(),source.name(),destination.name(),destinationPaddock,dp==null?null:dp.name(),v.occurred(),Instant.now(clock),c.userId(),a.version(),updated.version(),v.notes());transfers.insert(row,c.tenantId());TransferredEventDetails details=new TransferredEventDetails(c.farmId(),source.name(),v.destination(),destination.name(),destinationPaddock,dp==null?null:dp.name(),v.notes());events.record(c.tenantId(),c.farmId(),a.id(),AnimalEventType.TRANSFERRED_OUT,v.operation(),c.userId(),v.occurred(),updated.version(),details);events.record(c.tenantId(),v.destination(),a.id(),AnimalEventType.TRANSFERRED_IN,v.operation(),c.userId(),v.occurred(),updated.version(),details);out.add(new AnimalResult(a.id(),updated.version()));}return new Result(v.operation(),source,destination,dp,out);}
 private Result replay(TenantContext c,UUID op){List<HerdTransferRepository.Row> rows=transfers.byOperation(c.tenantId(),op);if(rows.isEmpty())throw new HerdOperationIdempotencyConflictException();HerdTransferRepository.Row first=rows.getFirst();HerdTransferRepository.Farm s=new HerdTransferRepository.Farm(first.sourceFarmId(),first.sourceFarmName()),d=new HerdTransferRepository.Farm(first.destinationFarmId(),first.destinationFarmName());PaddockSummary p=first.destinationPaddockId()==null?null:new PaddockSummary(first.destinationPaddockId(),first.destinationPaddockName(),null,PaddockStatus.ACTIVE,0);return new Result(op,s,d,p,rows.stream().map(x->new AnimalResult(x.animalId(),x.resultingVersion())).toList());}
 private Valid valid(UUID op,UUID dest,LocalDate date,String notes){if(op==null||dest==null||date==null||date.isAfter(LocalDate.now(clock)))throw new HerdAnimalCommandInvalidException();String n=notes==null?null:PosixEdgeWhitespace.trim(notes);if(n!=null&&(n.isEmpty()||n.indexOf('\0')>=0||n.codePointCount(0,n.length())>1000))throw new HerdAnimalCommandInvalidException();return new Valid(op,dest,date,n);} private void authorize(TenantContext c){if(!WRITE.contains(c.role()))throw new HerdTransferForbiddenException();} private String canonical(TenantContext c,Valid v,List<Animal> xs,UUID paddock){try{Map<String,Object> x=new LinkedHashMap<>();x.put("sourceFarmId",c.farmId().toString());x.put("destinationFarmId",v.destination().toString());x.put("destinationPaddockId",paddock==null?null:paddock.toString());x.put("occurredOn",v.occurred().toString());x.put("notes",v.notes()==null?"":v.notes());x.put("animals",xs.stream().map(a->Map.of("animalId",a.id().toString(),"expectedVersion",a.expectedVersion())).toList());return mapper.writeValueAsString(x);}catch(Exception e){throw new IllegalStateException(e);}} private record Valid(UUID operation,UUID destination,LocalDate occurred,String notes){} public record Animal(UUID id,long expectedVersion){} public record AnimalResult(UUID id,long version){} public record Result(UUID operationId,HerdTransferRepository.Farm sourceFarm,HerdTransferRepository.Farm destinationFarm,PaddockSummary destinationPaddock,List<AnimalResult> animals){public int transferredCount(){return animals.size();}}
}
