package com.gerenciadorrural.modules.inventory.api;

import com.gerenciadorrural.infrastructure.database.*;
import com.nimbusds.jose.*; import com.nimbusds.jose.crypto.MACSigner; import com.nimbusds.jwt.*;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.*; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.*; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.web.servlet.*; import org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder;
import java.math.*; import java.sql.Connection; import java.sql.ResultSet; import java.sql.Statement; import java.time.*; import java.util.*; import java.util.concurrent.*;
import static org.assertj.core.api.Assertions.assertThat; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;

@ActiveProfiles("test") @SpringBootTest(properties={"app.security.supabase.mode=HMAC","app.security.supabase.algorithm=HS256","app.security.supabase.issuer=https://auth.example.test/auth/v1","app.security.supabase.hmac-secret=test-only-hmac-key-with-at-least-32-bytes","app.security.supabase.audiences=authenticated","app.security.supabase.accepted-token-roles=authenticated"}) @AutoConfigureMockMvc
class InventoryConcurrencyAtomicityIntegrationTest extends SpringPostgresTestSupport {
 private static final String ISSUER="https://auth.example.test/auth/v1",SECRET="test-only-hmac-key-with-at-least-32-bytes"; @Autowired MockMvc mvc; UUID user,tenant,farm,product,one,two,three; String token;
 @BeforeEach void seed()throws Exception{PostgresTestEnvironment.clearUsers();user=UUID.randomUUID();tenant=UUID.randomUUID();farm=UUID.randomUUID();try(Connection c=PostgresTestEnvironment.adminConnection();Statement s=c.createStatement()){s.execute("insert into app.users(id,status) values('"+user+"','ACTIVE')");s.execute("insert into app.organizations(id,name,status) values('"+tenant+"','T','ACTIVE')");s.execute("insert into app.farms(id,tenant_id,name,status) values('"+farm+"','"+tenant+"','F','ACTIVE')");}member();token=token(user);product=createProduct();one=createLocation("A");two=createLocation("B");three=createLocation("C");}
 @Test void concurrentReplaysBalanceCreationAndCompetingIssuesRemainConsistent()throws Exception{for(int iteration=0;iteration<5;iteration++){UUID location=createLocation("R"+iteration);UUID operation=UUID.randomUUID();String same=receipt(operation,location,"1.0");List<Integer> replay=concurrent(same,same);assertThat(replay).containsExactlyInAnyOrder(200,200);assertThat(quantity(location)).isEqualByComparingTo("1.000000");assertThat(ledger(operation)).isEqualTo(1);UUID creation=UUID.randomUUID();List<Integer> created=concurrent(receipt(creation,location,"3"),receipt(UUID.randomUUID(),location,"4"));assertThat(created).containsOnly(200);assertThat(quantity(location)).isEqualByComparingTo("8.000000");UUID issueOne=UUID.randomUUID(),issueTwo=UUID.randomUUID();List<Integer> issues=concurrent(issue(issueOne,location,"7"),issue(issueTwo,location,"7"));assertThat(issues).contains(200,409);assertThat(quantity(location)).isEqualByComparingTo("1.000000");assertThat(ledger(issueOne)+ledger(issueTwo)).isEqualTo(1);}}
 @Test void oppositeTransfersUseDeterministicBalanceLockOrder()throws Exception{assertThat(call(receipt(UUID.randomUUID(),one,"10"))).isEqualTo(200);assertThat(call(receipt(UUID.randomUUID(),two,"10"))).isEqualTo(200);for(int iteration=0;iteration<5;iteration++){List<Integer> result=concurrent(transfer(UUID.randomUUID(),one,two,"1"),transfer(UUID.randomUUID(),two,one,"1"));assertThat(result).containsOnly(200);assertThat(quantity(one).add(quantity(two))).isEqualByComparingTo("20.000000");}}
 @Test void ledgerFailureRollsBackReceiptAndTransferAndCleansUpTrigger()throws Exception{assertThat(call(receipt(UUID.randomUUID(),one,"10"))).isEqualTo(200);installFailure();try{assertThat(call(receipt(UUID.randomUUID(),two,"3"))).isEqualTo(503);assertThat(quantity(two)).isEqualByComparingTo(BigDecimal.ZERO);assertThat(call(transfer(UUID.randomUUID(),one,two,"4"))).isEqualTo(503);assertThat(quantity(one)).isEqualByComparingTo("10.000000");assertThat(quantity(two)).isEqualByComparingTo(BigDecimal.ZERO);}finally{removeFailure();}try(Connection c=PostgresTestEnvironment.adminConnection();Statement s=c.createStatement();ResultSet r=s.executeQuery("select count(*) from pg_trigger where tgname='inventory_test_fail_ledger'")){r.next();assertThat(r.getInt(1)).isZero();}}
 private List<Integer> concurrent(String first,String second)throws Exception{ExecutorService executor=Executors.newFixedThreadPool(2);CyclicBarrier barrier=new CyclicBarrier(2);try{Future<Integer>a=executor.submit(()->{barrier.await(10,TimeUnit.SECONDS);return call(first);}),b=executor.submit(()->{barrier.await(10,TimeUnit.SECONDS);return call(second);});return List.of(a.get(20,TimeUnit.SECONDS),b.get(20,TimeUnit.SECONDS));}finally{executor.shutdownNow();}}
 private UUID createProduct()throws Exception{UUID id=UUID.randomUUID();try(Connection c=PostgresTestEnvironment.adminConnection();Statement s=c.createStatement()){s.execute("insert into app.inventory_products(id,tenant_id,name,code,category,base_unit,status) values('"+id+"','"+tenant+"','Produto','P','Insumo','KG','ACTIVE')");}return id;}private UUID createLocation(String name)throws Exception{UUID id=UUID.randomUUID();try(Connection c=PostgresTestEnvironment.adminConnection();Statement s=c.createStatement()){s.execute("insert into app.inventory_locations(id,tenant_id,farm_id,name,code,status) values('"+id+"','"+tenant+"','"+farm+"','"+name+"','"+name+"','ACTIVE')");}return id;}
 private String receipt(UUID op,UUID location,String quantity){return movement(op,"RECEIPT",null,location,quantity);}private String issue(UUID op,UUID location,String quantity){return movement(op,"ISSUE",location,null,quantity);}private String transfer(UUID op,UUID source,UUID destination,String quantity){return movement(op,"TRANSFER",source,destination,quantity);}private String movement(UUID op,String type,UUID source,UUID destination,String quantity){return "{\"operationId\":\""+op+"\",\"type\":\""+type+"\",\"productId\":\""+product+"\","+(source==null?"":"\"sourceLocationId\":\""+source+"\",")+(destination==null?"":"\"destinationLocationId\":\""+destination+"\",")+"\"quantity\":"+quantity+",\"occurredOn\":\"2026-09-10\"}";}
 private int call(String body)throws Exception{return call(post("/api/v1/inventory/movements"),body);}private int call(MockHttpServletRequestBuilder request,String body)throws Exception{request.header(HttpHeaders.AUTHORIZATION,"Bearer "+token).header("X-Organization-Id",tenant).header("X-Farm-Id",farm).contentType(MediaType.APPLICATION_JSON).content(body);return mvc.perform(request).andReturn().getResponse().getStatus();}
 private BigDecimal quantity(UUID location)throws Exception{try(Connection c=PostgresTestEnvironment.adminConnection();Statement s=c.createStatement();ResultSet r=s.executeQuery("select coalesce(quantity,0) from app.inventory_balances where tenant_id='"+tenant+"' and farm_id='"+farm+"' and location_id='"+location+"' and product_id='"+product+"'")){return r.next()?r.getBigDecimal(1):BigDecimal.ZERO;}}private int ledger(UUID operation)throws Exception{try(Connection c=PostgresTestEnvironment.adminConnection();Statement s=c.createStatement();ResultSet r=s.executeQuery("select count(*) from app.inventory_movements where operation_id='"+operation+"'")){r.next();return r.getInt(1);}}
 private void installFailure()throws Exception{try(Connection c=PostgresTestEnvironment.adminConnection();Statement s=c.createStatement()){s.execute("create function app.inventory_test_fail_ledger() returns trigger language plpgsql as $$ begin raise exception 'inventory test fault'; end $$");s.execute("create trigger inventory_test_fail_ledger before insert on app.inventory_movements for each row execute function app.inventory_test_fail_ledger()");}}private void removeFailure()throws Exception{try(Connection c=PostgresTestEnvironment.adminConnection();Statement s=c.createStatement()){s.execute("drop trigger if exists inventory_test_fail_ledger on app.inventory_movements");s.execute("drop function if exists app.inventory_test_fail_ledger()");}}
 private void member()throws Exception{UUID membership=UUID.randomUUID();try(Connection c=PostgresTestEnvironment.adminConnection();Statement s=c.createStatement()){s.execute("insert into app.organization_memberships(id,tenant_id,user_id,role_key,status,farm_scope_mode) values('"+membership+"','"+tenant+"','"+user+"','OWNER','ACTIVE','SELECTED_FARMS')");s.execute("insert into app.membership_farm_scopes(tenant_id,membership_id,farm_id) values('"+tenant+"','"+membership+"','"+farm+"')");}}private static String token(UUID id)throws Exception{JWTClaimsSet claims=new JWTClaimsSet.Builder().issuer(ISSUER).audience("authenticated").subject(id.toString()).claim("role","authenticated").issueTime(new Date()).expirationTime(Date.from(Instant.now().plusSeconds(300))).build();SignedJWT jwt=new SignedJWT(new JWSHeader(JWSAlgorithm.HS256),claims);jwt.sign(new MACSigner(SECRET.getBytes()));return jwt.serialize();}
}
